### ISSUE TITLE
[Feature] show balance in Fiat

### ISSUE THREAD

**Issue by prusnak** [ACINQ/eclair-mobile#10]
There is an option to select Fiat currency in settings, but there is no fiat balance shown anywhere in the TX history.

I would expect to see the fiat equivalent of total balance at least.

**Comment by dpad85** [comment]
If you click on the wallet balance (top blue section), most amounts field in the app will switch from btc to fiat.

**Comment by prusnak** [comment]
Great, thank you. Closing
