### ISSUE TITLE
The future ability to receive payments without having to generate payment requests

### ISSUE THREAD

**Issue by d4amenace** [ACINQ/eclair-mobile#105]
What about the ability for the sender to just send a payment to the receiver without the receiver having to first issue a payment request if you are already directly connected through a channel to the receiver? This would allow for lightning tips without having to host a tip bot payment request creating plugin on an expensive server.

**Comment by sstone** [comment]
The current LN protocol requires the receiver to actively initiate the payment workflow: the receiver creates a payment preimage, sends its hash to the sender (typically by displaying a QR code).
There have been discussions on how to enable recurring payments or donations (see https://github.com/lightningnetwork/lightning-rfc/issues/447 for example), and it's a feature that has been requested quite often so we'll try to add it to the next version of the protocol.
