### ISSUE TITLE
Opened two channels, but they don't show up in any ln explorer

### ISSUE THREAD

**Issue by bloctavius** [ACINQ/eclair-mobile#107]
Here are the two channel IDs that I have:
0e0bfbf8df0fd36d6183f3727f652b982830c3ab6eb5facf076246c1642d2f3b
8a02ea45a466266c75109d516c8699ec19dd7d502384088e19b451f285e61bd9
The states are both "NORMAL" but they don't show up on any ln explorer...
My alias is Bloctavius and my node URI is 02ab593dbff6cbc273b5bc6dedea049e898eb0df6871324d54b202475451e35731@148.75.243.60:9735

Any insights would be helpful

**Comment by sstone** [comment]
As much as possible please ask support questions on https://gitter.im/ACINQ/eclair, we use github for strictly technical issues. Channels opened with our mobile app are not announced and will not show on LN explorers (see https://github.com/ACINQ/eclair-wallet/wiki/FAQ#i-dont-see-my-eclair-wallet-node-on-ln-explorers-)
