### ISSUE TITLE
"bad concurrent query_short_channel_ids" error

### ISSUE THREAD

**Issue by gabrieldodan** [ACINQ/eclair-mobile#111]
Hi,

I am trying to open a LN channel but I always get "bad concurrent query_short_channel_ids" error and the channel is closed automatically ...I have eclair wallet version 0.3.5 installed. Any idea? 

Thanks!

**Comment by sstone** [comment]
Which node are you trying to open a channel to ?

**Comment by gabrieldodan** [comment]
This is the node 024655b768ef40951b20053a5c4b951606d4d86085d51238f2c67c7dec29c792ca@88.98.213.235:9735

But after a few tries it worked finally ... haven't changed anything, maybe it was just a temporary issue.

**Comment by sstone** [comment]
This error is linked to a new feature ("channel range queries") that was added to the LN specs recently, and I think that lnd recently fixed a few errors related to that feature so maybe the node was running an old version and upgraded ? I'm closing this for now. Thanks!
