### ISSUE TITLE
"Send" and "add channel" buttons greyed out on Android Pie

### ISSUE THREAD

**Issue by hypevhs** [ACINQ/eclair-mobile#112]
The "send funds" and "add lightning channel" floating-action-button is greyed out. I'm running mainnet eclair on a Google Pixel, which updated to Android Pie very recently. I haven't used this app in a while, though.

- Have tried to restart the app, restart device, clear cache, close LN channels (uncooperatively)
- Have not tried to clear data
- "Network Info" shows _block height_ of 0, and _N/A_ for electrum server

If you need additional information please ask. If this is PEBCAK please close.

**Comment by hypevhs** [comment]
Forgot to mention I am running 0.3.5 from Google Play.

**Comment by dpad85** [comment]
This is a networking problem. The buttons are greyed out because the wallet cannot connect to any electrum servers. Are you connected to a Wi-Fi network? If so, can you try switching to another Wi-Fi network and restart the app?

**Comment by hypevhs** [comment]
It seems that my Wi-Fi networks block some traffic, as I was connecting to `[redacted].eu:50001`. When connecting via mobile network, everything works as expected.

I propose that an indication be added if no server is reachable. I know the "Connection to Electrum Server lost" toast sometimes appears, something similar to that would be useful.

**Comment by dpad85** [comment]
That's a good point. There is not enough feedback to the user in this case.
Thanks!

**Comment by Giszmo** [comment]
GAH! The fact the wallet does sync while it fails to connect to some server is making it very very confusing. If I had seen a sync error or something red, I would have assumed to have connection problems but the blue "connecting to" didn't mean "failing to connect to" to me.
