### ISSUE TITLE
Custom fee issues - Eclair Mobile v0.3.7 Testnet

### ISSUE THREAD

**Issue by molxyz** [ACINQ/eclair-mobile#113]
It's great that we can change on-chain transaction fees on Eclair Mobile before we send the transactions. However, in order to do this we have to play with the app by pressing on the amount number next to `FEES` before `sat/byte` before the app lets us change the fee amount per byte.  There is a `CUSTOM` button but it doesn't show up until we start to change this fee amount. But this button will change your fee amount if you touch it, I think the button `CUSTOM` is pretty much useless. 

My request is: Could you please change this and and create a visible and working button for `CUSTOM` that will let us set our on-chain tx fees in a beter way? 

I've had this testing done on two Android phones. versions 7.0 and 7.1.1.  Once the tx fee is set and ready to go, the app shows two buttons for `CANCEL` and `PAY` clearly on Android version 7.1.1.  But for Android version 7.0 these two buttons are not positioned correctly:  https://i.imgur.com/CQa0J4Y.png .

Thank you for all your wonderful work.

**Comment by dpad85** [comment]
Hi molxyz,

The `CUSTOM` button just shows that the user has entered a custom fee value. If you press the button, you will switch back to one of the predefined fee estimation, either `SLOW`, `MEDIUM`, or `FAST`. I understand that it can be confusing at first. 

Two improvements could be made:

* change the style of the `CUSTOM` button when the user enters a custom fee value. 
* underline the fee value input to show that the value can be changed


About the `CANCEL` and `PAY` buttons, that's an issue indeed, on smaller screens size with a warning message, the bottom content of the payment page is cut off. The user should be able to scroll down.

Thanks!
