### ISSUE TITLE
Wallet giving me too much money   /s

### ISSUE THREAD

**Issue by STAWKEYE** [ACINQ/eclair-mobile#123]
Upon opening a payment channel the funds ultimately move from on-chain BTC to Lightning, which is shown as 2 separate balances on main eclair screen. While the opening Tx is in mempool awaiting inclusion into the blockchain the LN balance has updated but the BTC balance has not, therefore double-counting funds. The overall total at the top reflects double-counting. This is presumably all graphical of course but I thought I'd bring it up so that people don't get too excited...

**Comment by dpad85** [comment]
Hello,
The wallet UI should indeed ignore balance of channels in `WAIT_FOR_ACCEPT_CHANNEL` state.
Thanks!

**Comment by STAWKEYE** [comment]
I would like to add that this particular channel wound up being frozen somehow and I've tried force-closing it both on the Eclair mobile wallet side as well as the Eclair Lightning Node side (it is a channel from my mobile to my own LN node). I'm not sure how to un-stick it at this point; the (duplicate) force-close initiated by my full node is only 12 hours old, however the original force-close initiated by my mobile wallet is roughly 3 days old.

I know the typical lockup period is 144 blocks, but I don't see a place in Eclair (mobile or full node) to explicitly define that upon channel creation, and so I assume it is indeed set to 144 blocks.

The above mentioned overall balance is now showing correctly and so if this channel were to be frozen forever no funds are lost, but I'm sharing in case this stuck channel is what ultimately caused the double-counting referenced earlier, and not what dpad85 mentioned.

**Comment by dpad85** [comment]
> I know the typical lockup period is 144 blocks, but I don't see a place in Eclair (mobile or full node) to explicitly define that upon channel creation, and so I assume it is indeed set to 144 blocks.

You cannot configure this from the mobile wallet. For your desktop node, take a look at this line in the conf: https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/resources/reference.conf#L56
