### ISSUE TITLE
can't build on android studio

### ISSUE THREAD

**Issue by equisde** [ACINQ/eclair-mobile#127]
it says could not find those plugins i've set google repo instead of jcenter

Could not find org.greenrobot:greendao-gradle-plugin:3.2.2.
Searched in the following locations:
    https://dl.google.com/dl/android/maven2/org/greenrobot/greendao-gradle-plugin/3.2.2/greendao-gradle-plugin-3.2.2.pom
    https://dl.google.com/dl/android/maven2/org/greenrobot/greendao-gradle-plugin/3.2.2/greendao-gradle-plugin-3.2.2.jar
Required by:
    project :

**Comment by dpad85** [comment]
Hello,

The google maven repo only contains google artifacts as you can see here: https://dl.google.com/dl/android/maven2/index.html

If you remove the `jcenter` repository, you may not be able to retrieve some dependencies. You should not remove it.

In any case, the `greendao-gradle-plugin` is available from these repos:

* http://central.maven.org/maven2/org/greenrobot/greendao-gradle-plugin/3.2.2/
* https://jcenter.bintray.com/org/greenrobot/greendao-gradle-plugin/3.2.2/
