### ISSUE TITLE
BTC~USD price shown is grossly incorrect

### ISSUE THREAD

**Issue by montvid** [ACINQ/eclair-mobile#134]
1 BTC shown in the app as 4.918.40 USD while the price on coinmarketcap.com is 3.280.1 USD. What service is used for price discovery?

**Comment by dpad85** [comment]
Hello,

We use the blockchain.info ticker API for price discovery (https://blockchain.info/ticker) which as of now shows a price of 3,289 USD.

The price is regularly refreshed (when the app starts, and every 20 min after that), though if you do not have access to the internet, or if for whatever reason your device cannot reach the blockchain.info API, the app will use the latest price it knows, which in your case is 4,918 USD.

**Comment by montvid** [comment]
I use LineageOS Android  8.1 via WIFI, I pushed a f-droid link to donate bitcoin, the eclair wallet booted and showed the Pay dialog, entering 1 BTC the wallet showed the old USD price info. I haven't booted the wallet for some days. Trying now again the USD price is refreshed correctly.

It seems the USD price is not refreshed instantly when the app starts and **shows the Pay dialog box**. Or as you say my device could not reach the blockchain.info API while being online via wifi. Thanks for the reply, I can close the bug report if you think it's not a bug.

**Comment by dpad85** [comment]
You can leave the issue open, it's not a bug per se but it's bad UX and there are a few things that can be improved. Thanks.
