### ISSUE TITLE
Incorrect insufficient funds reported - plenty of funds in wallet

### ISSUE THREAD

**Issue by Heebron** [ACINQ/eclair-mobile#136]
My wallet contains significantly more BTC then the amount I am attempting to use to open a channel. No matter what node I pick, including the ACINQ node, I receive an insufficient funds error and the channel immediately closes.

I am attempting to open a channel to node: 
```
0242a4ae0c5bef18048fbecf995094b74bfb0f7391418d71ed394784373f41e4f3@18.184.237.59:9735
```
with 3054206 satoshis. ~ $100 USD

The channel briefly displays in the GUI, then I get the insufficient funds error and the channel closes and disappears.

My BTC wallet (using bitcoind) contains over 0.5 BTC.

I tried opening channels to several different nodes with the same behavior.

Version: eclair-node-gui-0.2-beta8-52821b8.jar
jdk: 1.8.0_181
O/S: Linux 18.04 LTS

**Comment by dpad85** [comment]
Hello, this is the repository for the mobile Eclair Wallet android application. Your issue is related to eclair (for servers/desktop), not the android app.

Could you recreate the issue here: https://github.com/ACINQ/eclair/issues
Thanks

**Comment by Heebron** [comment]
This may be due to the wallet being locked? I unlocked my wallet and was able to fund a channel. Is there anyway for your client to detect that the wallet is locked and report that instead of insufficient funds?

**Comment by Heebron** [comment]
Oops - I'll move over to the other project.
