### ISSUE TITLE
Remote Failure

### ISSUE THREAD

**Issue by corbimos** [ACINQ/eclair-mobile#14]
https://imgur.com/a/CQMb4

Opened a channel with ACINQ and can't pay for anything on block stream store. Is this just a routing issue where ACINQ does not have an open channel to the LN store?

**Comment by dmitryplatonov** [comment]
I am have the same issue with different store and my channel is opened to ACINQ.

**Comment by victorperin** [comment]
Same here. Seems to be a problem with the acinq node.

Trying to open channel to another node, but right now I'm locked at `WAIT_FOR_FUNDING_LOCKED`.

**Comment by pm47** [comment]
This is simply a liquidity issue: everyone is trying to pay the same merchants, leading to channels being unbalanced quite fast. We are adding more capacity but can't open more than c-lightning.

> Trying to open channel to another node, but right now I'm locked at WAIT_FOR_FUNDING_LOCKED.

Depending on the destination node, they may require more confirmations that eclair, in that case you just need to wait.
