### ISSUE TITLE
Allow a failed transaction to be re-attempted

### ISSUE THREAD

**Issue by pshep** [ACINQ/eclair-mobile#144]
When a transaction fails due to no route (and maybe other reasons), allow the transaction to be reattempted via the GUI.
I found that after allowing the network scan to complete, I had to re-scan the same QR code to re-send the same transaction.
Maybe have a few options for failed transactions? Retry/cancel etc.

**Comment by bidelakbari** [comment]
I have the same problem here. for some payments which I have no direct channel with the receiver, my LN node retries and eventually pays after about 20 retry. I know adding "Number of retry" option would be a bad UX choice but I believe it is necessary, now that the capacity of some nodes are low

**Comment by artlav** [comment]
I'll add to that a request for a cleaner indication of the payment being retried.

Right now if i re-scan the same QR code the payment stays listed as "Failed" while it's being re-attempted. This is quite confusing, you should either add a new line for each attempt or to change the status back to pending.
