### ISSUE TITLE
faq state about 24 words but wallet only give 12 words

### ISSUE THREAD

**Issue by manreo** [ACINQ/eclair-mobile#147]
This is from the faq
> Can I restore my seed on another bitcoin wallet ?
> Yes. Your seed (the **24** words that eclair will display when you start it for the first time) is a standard BIP30 seed with a BIP49 derivation path, which can be restored on any BIP49 compliant wallet. With Electrum for example, you would choose "I already have a seed", tick the BIP39 checkbox,and then select BIP49.

But actually you only get 12 words

**Comment by dpad85** [comment]
Good catch, thanks, it's fixed!
