### ISSUE TITLE
"Tune energy settings" notification is not shown

### ISSUE THREAD

**Issue by akumaigorodski** [ACINQ/eclair-mobile#157]
I have a Mi5 phone, Android version 8.0.0, MIUI version 10.2.2.0 and it is well known that by default it does not run periodic channel breach checks in a background. 

As far as I know Ecliar mobile should react to this by showing a "Tune energy settings" notification once user opens an app and it detects that no background check has happened during the last 5 days. This also does not happen in my case, it's been 6+ days since I installed and used an app but there are no notifications when I open it.

Checking "network info" page shows "background check: never run".

**Comment by dpad85** [comment]
Hi Anton,

Thanks for reporting this, there is a bug. Right now the message is only shown if the background check has run at least once, and then has stopped running.
