### ISSUE TITLE
Upon channel opening: Peer sent error

### ISSUE THREAD

**Issue by ghost** [ACINQ/eclair-mobile#169]
**Describe the error**
When I want to connect to any node and open a channel with receive activated, upon setting the capacity + fee and clicking open, following error shows `Failed to open channel: peer sent error: 'ByteVector(1 bytes, 0x01)'`

**Version**
Running Eclaire mobile v0.4.3 mainnet

**Comment by pm47** [comment]
How many nodes have you tried? I don't see a bug in Eclair Mobile there, just a peer returning an (unintelligible) error. I think `lnd` sends that weird `01` error sometimes, but I don't know what causes it.

**Comment by ghost** [comment]
I've tried Bitrefill, Lightning Power Users, Yalls, Tippin, and several other nodls. It worked only to open a channel to Acinq...

**Comment by pm47** [comment]
I can't reproduce. @dpad85 any idea?

**Comment by dpad85** [comment]
I could open a channel with the [Lightning Power Users](https://1ml.com/node/0331f80652fb840239df8dc99205792bba2e559a05469915804c08420230e23c7c) node without any issues. AFAIK this node is using lnd.

**Comment by ghost** [comment]
I've tried the exactly same again today, and everything worked fine.
Odd error, it looks like it was all on my side...

Closing the issue since neither you nor I can reproduce it now.
