### ISSUE TITLE
[Bug] "Error in payment request..." Cannot receive any lightning payments.

### ISSUE THREAD

**Issue by ParmuSingh** [ACINQ/eclair-mobile#174]
I have an inbound channel from ACINQ but I cannot receive any lightning payments because I cannot generate an invoice.

![Screenshot](http://imgur.com/a/XiKjCiL)

I've done receiving transaction before but as of today (probably after inbound capacity from ACINQ) I've got this error.

I can do on chain transaction but no off chain. Please see screenshot.

Screenshot: http://imgur.com/a/XiKjCiL

Its a Samsung Galaxy S7 Edge - India.

Edit: I do have 1 peer offline but its an outbound channel.

**Comment by ParmuSingh** [comment]
It was because one of my peer was offline. Its online now and the error is gone. I don't know how that matters, my transaction didn't even go through it.

**Comment by dpad85** [comment]
Hello

Thanks for reporting this. As you mentioned, this is a bug that can happen when your peer is offline, and you have not receive any `ChannelUpdate`. This will be fixed in the next release.

**Comment by kikoncuo** [comment]
Same error, I'm successfully connected to 2 peers, one of them is offline, is this normal? we won't be able to receive payments if any of our peers goes down?
