### ISSUE TITLE
0 balance in Eclair app

### ISSUE THREAD

**Issue by kjellberg** [ACINQ/eclair-mobile#175]
Hello,

My app shows 0 balance after receiving an onchain transaction. I've been waiting for 6 confirmations. 

- Receiving address was updated to a new one. So it knows that the first one has been used.
- I've confirmed that I sent to the correct address by importing my backup seed to the Electrum desktop app. Balance shows up there.

Google Pixel 2, Android version 9

Is there anything I can do to help debug this?

Thanks!

**Comment by dpad85** [comment]
Hello,

- What version are you running? You can see that in Menu > About/Help.

- Are you synced with the electrum server? (if you're not you'll see a `Syncing from ...` at the bottom of the home page). Do you see the incoming transaction in the list?

- What block height do you see in Menu > Network Info?

You can also enable logs in Menu > Settings > Logging > Local File (restart the app afterwards) and send us the logs (mobile@acinq.co)

**Comment by kjellberg** [comment]
I see the transactions now. I guess it wasn't fully synced then. I never checked the block height but the `Syncing from ...` message disappeared after a minute or so. Latest version(?) downloaded from Google Play, 0.4.4.

**Comment by dpad85** [comment]
There was (and still is, I believe) a DoS attack against electrum servers (see https://twitter.com/ElectrumWallet/status/1114987055736655873) which could explain why retrieving your transactions was very slow.

If your problem is fixed, please close this issue.
Thanks.
