### ISSUE TITLE
Google Drive dependancy is disgusting.

### ISSUE THREAD

**Issue by PC-Admin** [ACINQ/eclair-mobile#179]
Please provide an alternative to using Google Drive to secure a LN channel, not everyone wants to run NSA software all day.

Wallet is unusable for me due to this, i want to use Lightning but how can i do it securely? Eclair expects me to have several hundred megabytes of bullshit on my phone.

Cheers

**Comment by pm47** [comment]
Backups are encrypted, and if you are on Android you are already running Google software.

That said GDrive is indeed far from ideal, see #126.
