### ISSUE TITLE
Difference between channel capacity on my side and "can send" amount

### ISSUE THREAD

**Issue by ParmuSingh** [ACINQ/eclair-mobile#182]
I received 50,000 sats so channel capacity on my side is 50,000sats (it was empty before) but when I see the channel details it says my ability to send from that channel is 40,000.

Why the difference between what's on my side and what I can send? If I can't send its not my money? Does this mean I lose money? This is the case with every channel.

Screenshots: http://imgur.com/a/mKeYcTc

**Comment by dpad85** [comment]
Hello,

There is a difference between the balance of the channel and what you can send. A channel has to keep a minimum reserve that it cannot spend (as per the [Lightning specification](https://github.com/lightningnetwork/lightning-rfc/blob/090af1a22d00eb7ad57419eb45d7e206610aeade/02-peer-protocol.md#rationale)). Rationale is to make sure that "Each side of a channel [...] has something to lose if it were to try to broadcast an old, revoked commitment transaction". These funds are not lost in any way, you will get them back should you close the channel. 

You can see the reserve in the channel's details page. The recommended value is 1%. In your case, the channel has a 1,000,000 sat capacity, so its reserve is 10,000 sat. The amount you can send is 50,000 - 10,000 = 40,000 sat

Note: if you are the funder of the channel (not your case here) there also is the commitment fee, which estimates the onchain fee of the transaction closing the channel.

For support questions, please join our Gitter: https://gitter.im/ACINQ/eclair-mobile

**Comment by ParmuSingh** [comment]
@dpad85 that doesn't seem right. I have another channel of 100,000sats capacity with ~97,000sats on my side but my spendable amount is ~75,000sats.

1% of 100,000 = 1000sats. So my spendable amount should be 97000-1000=96,000sats but is 75,000 instead. Why would that be?

**Comment by mmortal03** [comment]
I tried googling eclair "total can send", and eclair "can send", and not many results come up. This GitHub issue seems to get closest to a proper answer, though @ParmuSingh 's last question seems to be a good one. I'm currently seeing a balance on my wallet of $7.80, but "total can send" is 0.00. It's on a channel that's been open a while, from which I've sent out a handful of transactions. I suspect other users would wonder what's going on if they ran into this issue.

![bugreport-potter-OPSS28 85-17-6-2021-01-05-14-41-10](https://user-images.githubusercontent.com/8298277/103696723-7731ac00-4f64-11eb-9a5d-db3869839a21.png)

**Comment by t-bast** [comment]
> Note: if you are the funder of the channel (not your case here) there also is the commitment fee, which estimates the onchain fee of the transaction closing the channel.

This is the other reason your "can send" balance is lower: when on-chain fees are high, the fee for the commitment tx can be quite high as well. You can find the current feerate used by clicking on the channel and then "Show channel raw data".

**Comment by mmortal03** [comment]
> > Note: if you are the funder of the channel (not your case here) there also is the commitment fee, which estimates the onchain fee of the transaction closing the channel.
> 
> This is the other reason your "can send" balance is lower: when on-chain fees are high, the fee for the commitment tx can be quite high as well. You can find the current feerate used by clicking on the channel and then "Show channel raw data".

Thanks! That's probably it. Does the unit Kw stand for kiloweight? Maybe there could be some practical estimate of the impact of this feerate on transaction feasibility, exposed to the user without them having to dive into the raw data? I assume transaction weight isn't known until the specific transaction amount is entered? 

I'm seeing in the code for conversion of this feeratePerKw value discussed here: 
 https://github.com/ACINQ/eclair/issues/1188

For reference, my Channel Details say:

 Current Balance: 23,051.113 sat
 Minimum channel reserve: 4,293 sat
 
 And my Channel Raw Data say:
 
 "feeratePerKw": 21714

**Comment by t-bast** [comment]
> Does the unit Kw stand for kiloweight

Yes exactly.

> "feeratePerKw": 21714

With that feerate and your channel reserve, around 20k sats will be reserved, does that match what you observe?

**Comment by mmortal03** [comment]
> With that feerate and your channel reserve, around 20k sats will be reserved, does that match what you observe?

Yeah, it's in the ballpark. I'll have to look at the formulas in the code when I get a chance.
