### ISSUE TITLE
[Question] Where are channels stored in device?

### ISSUE THREAD

**Issue by ParmuSingh** [ACINQ/eclair-mobile#183]
I want to save my channels (NOT on google drive even though they're encrypted), where can I find them? I know I can just get channel details from in-app but I actually want the file its reading from. I also wanted to try some editing and see what happens. I'm going to try this with test btc so its safe. I'm on Android.

**Comment by dpad85** [comment]
For the backup mechanism, we want to provide an option for on-device backup alongside with Google Drive.

The actual channels file used for by the app is in an internal file that you cannot access in a released application. If you want to experiment, you can either:
- build the Android application in debug mode (use the `testnet` branch)
- (recommended) use eclair on desktop/server (see https://github.com/ACINQ/eclair) which is the same software that runs on your phone, but internal files will be easier to access, and you can use regtest which is much better for testing.
