### ISSUE TITLE
Error at start: "Could not start eclair. - RESTART"

### ISSUE THREAD

**Issue by boskowski** [ACINQ/eclair-mobile#191]
I'm using Eclair 0.4.6 on Android 7.1.1. Today it suddenly refused to start: After entering PIN it terminates with "Could not start eclair. - RESTART".

I've tried to clear storage/cache and to recover with seed, but after it restores the backup from GDrive I'm back at square one.

I've searched for a log file, but /sdcard/Android/data/fr.acinq.eclair.wallet.mainnet2 only contains an empty "files" directory.

Is there any way to recover  the funds locked in channels?

**Comment by pm47** [comment]
Could be a connectivity issue, have you tried over wifi?

**Comment by boskowski** [comment]
Thanks for the feedback! Apparently you're right, it works over wifi, but I'm quite puzzled about the cause as I didn't otherwise experience connectivity issues with the LTE connection.
