### ISSUE TITLE
How to migrate to the new app without the seed

### ISSUE THREAD

**Issue by Illidanek** [ACINQ/eclair-mobile#192]
I haven't used my Eclair wallet for a while (have been playing with LN on desktop) and I see there's a new version I need to download.

However, I can't find my seed anywhere and I can't display it in the app. I also can't transfer the funds to another wallet (because the app is deprecated).

Surely the keys are somewhere on the phone? I know the PIN so I should be able to decrypt them.

Can someone please help me recover my funds?

**Comment by pm47** [comment]
What version is your app?

**Comment by Illidanek** [comment]
0.3.0

**Comment by pm47** [comment]
[This tutorial](https://github.com/ACINQ/eclair-mobile/wiki/Recover-funds-stuck-in-CLOSING-state-from-Eclair-Wallet-0.3.0) should help you enable the send button so you can get your funds out.

It has been quite some time since we haven't needed it, so let me update the server, and I'll tell you when it is ready.

**Comment by Illidanek** [comment]
Oh wow, thanks so much - I'll wait for your signal.

**Comment by Illidanek** [comment]
Hey there @pm47, have you managed to check the server? I have tried what you said a few days ago, and the DNS worked fine, however nothing changed on the app, sending still disabled. Now I tried it again and the DNS is not working.

**Comment by pm47** [comment]
Hey, we had to resync the blockchain and it took more time than expected.
Actually beefed up the server this morning. Sorry for the delay, but stay
tuned we are on it

**Comment by pm47** [comment]
@Illidanek you can go ahead and follow the tutorial

**Comment by Illidanek** [comment]
Worked!! Thanks a million dude, the transaction is on its way out <3
