### ISSUE TITLE
What just happened?

### ISSUE THREAD

**Issue by nomogi77** [ACINQ/eclair-mobile#199]
I just set up my eclair wallet and linked my lightning account and went to look at who I wanted to tip and without a confirm amount or anything even before my wallet was ready. The 20 dollars I funded my account with went to one person that can't be how this works my wallet said wait for funding or something and now amount sent $17.00 or aboùt wtf?

**Comment by nomogi77** [comment]
It was a very unclear process.

**Comment by nomogi77** [comment]
Oh ok I see you little game there crooks! Man so unprofessional it is only a little money but I don't have thousands of people losing a little money to me all day everyday.

**Comment by nomogi77** [comment]
Damn!

**Comment by pm47** [comment]
Using that language instead of explaining calmly what your problem is won't get you anywhere.

I'll give you one more chance to clearly document your issue before I close it.

**Comment by nomogi77** [comment]
Go ahead wow!
