### ISSUE TITLE
Channel closed automatically

### ISSUE THREAD

**Issue by ParmuSingh** [ACINQ/eclair-mobile#204]
So this is the second time this is happening and I have no idea why. I had a channel with sideshift and when I opened my app it automatically started closing that channel.

I've lost reserve 20,000sats TWICE and I honestly don't have a lot of money to begin with. Why tf do you have to automatically close channels?

![Channel automatically closing](https://i.imgur.com/LtH0xiJ.jpg)  

Here it says my closing balance was 140ksats:

![Here it says my closing balance was 140ksats](https://i.imgur.com/3iaLsoj.jpg)

Here it says I only got 114ksats back to on-chain:

![Here it says I only got 114ksats back to on-chain](https://i.imgur.com/kma1kRu.jpg)

**Comment by sstone** [comment]
`Why tf do you have to automatically close channels?`

Don't use language like this. Be civil, concise yet specific as much as possible. 
That channel was not closed "automatically", it was closed by sideshift, not by eclair mobile. Did you contact them ? they should be able to tell you why if you give them the channel id. 
Also, we use github for technical issues, not for general support/question (please use https://gitter.im/ACINQ/eclair-mobile instead).

**Comment by pm47** [comment]
Also the `20000` sats have nothing to do with channel reserve, they have been paid as network fees (maybe sideshift closed the channel during a fee spike?).

**Comment by ParmuSingh** [comment]
appologies for language. The transaction fees was only 6000sats https://www.blockchain.com/btc/tx/46cd3c068429a40c4641c814d878027ccde55f055a944e31276f35981d53037d dunno why it costed 20ksats

**Comment by pm47** [comment]
There are 3 linked transactions that spend each other:

type | txid | fees
-----|------|-----
funding | c48edbd325458731e9900074a178c677e7a71ae4829200ac8cc372fe32aa8a66 | 0.00000801
commit | 62aca6627acc0d7eab5eaa3ac624c3e8e3be036601456d750bdc97d7299218b4 | 0.00022235
refund | 46cd3c068429a40c4641c814d878027ccde55f055a944e31276f35981d53037d | 0.00006211

The commit transaction has to have a pretty high fee for technical reasons, but it is not supposed to be published except in case of problems. You may want to pick more reliable peers if you want to minimize that kind of unexpected behavior.

**Comment by pm47** [comment]
To be 100% clear: in the normal case you would have a funding tx and a closing tx.
