### ISSUE TITLE
Paying invoice after expiry

### ISSUE THREAD

**Issue by jackeveritt** [ACINQ/eclair-mobile#209]
I was able to pay an expired lightning invoice in version 0.4.8, android.

1) Open an invoice in the app to reveal the payment screen.
2) Tap on the amount field to show the keyboard (I am not sure if the step is required, but it helps keep the app in focus - the screen must not go to sleep)
3) Wait until the invoice should have expired
4) The screen is still on the payment screen with the keyboard
5) Tap on the Pay button

Result: Payment goes through to my LND via BTCPayServer.

I would expect this to not go through because according to the bolt 11 spec:

> A payer:
>     after the timestamp plus expiry has passed:
>         SHOULD NOT attempt a payment.

Source: https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md#payer--payee-requirements

**Comment by jackeveritt** [comment]
I tried the same proceedure to a C-Lightning Node and although eclair still attempted the payment, it was rejected with the error:

"incorrect payment amount or unknown payment hash"
RemoteFailure

**Comment by t-bast** [comment]
Thanks for reporting this issue @jackeveritt 
This is an easy fix, we'll include that before our next release.
I'm very surprised that the payment goes through to the lnd node. They should reject the payment like c-lightning does.
