### ISSUE TITLE
Trouble sending to certain bech32 addresses

### ISSUE THREAD

**Issue by friendsofbitcoin** [ACINQ/eclair-mobile#217]
**Description**

Cannot send onchain tx to bech32 address created by a brd wallet for ios either by scanning QR code or pasting address. Could send to bech32 address generated by purse.io however. Was able to send whole remaining onchain balance to a P2SH segwit after sending native segwit to purse.io.

Error message received is "cannot send transaction" after typing in correct pin. Attempted 4 times with failure on same server.

**Version**
Eclair android version 0.4.8

**Device or machine**
Android 7.1.1 build - 1 april 2018

HW - LG-M700F

**Additional info**
Log files reflect this error response-

"f.a.eclair.wallet.App - could not send bitcoin tx null with cause Ask timed out on [Actor"

The native segwit address created by Brd was correct because we shared it directly from wallet and because I paid invoice with ledger live just fine.

**Comment by sstone** [comment]
Can you give us an example of a bech32 address that we cannot use ? If you don't want to share them publicly (which would be very understandable) you can contact us on https://gitter.im/ACINQ/eclair-mobile and we can chat privately.

**Comment by friendsofbitcoin** [comment]
No problem, I sent you the address and logs. I noticed this same problem with past bech32 addresses created by Brd as well so not isolated issue

**Comment by friendsofbitcoin** [comment]
I reinstalled a fresh version of eclair and restored with seed phrase and new BTC and sent btc to same native segwit address that was previously being blocked by eclair and it worked just fine this time. Thus the issue could have been either due to 

1- perhaps a fresh installed of app solved the problem as my previously eclair app weent through many upgrade iterations?

2- intermittent txs being blocked due to electrum server problems that just coincidentally always failed for brd generated bech32 addresses but not other wallets
