### ISSUE TITLE
Cannot enable GDrive backup, stuck at blank screen

### ISSUE THREAD

**Issue by andronoob** [ACINQ/eclair-mobile#222]
Eclair mobile mainnet 0.4.9
LineageOS 16 with OpenGapps nano

There would be a toast saying "Sign-in Failed" if I click somewhere outside this blank window.

![Screenshot_Google_Play_](https://user-images.githubusercontent.com/4075106/66712482-d2133c80-edcf-11e9-827a-298fbfdc6fc6.png)

**Comment by andronoob** [comment]
I have reflashed with stock OpenGapps, but the problem still persists.
[logcat.txt](https://github.com/ACINQ/eclair-mobile/files/3723044/logcat.txt)

**Comment by dpad85** [comment]
Hello,

It seems that your device cannot reach the Google Drive API, or at least get the Consent screen to grant permission. Let's try a few things:

- Can you use switch to another WiFi network?

- Can you remove any access Eclair mobile has to your Google Drive, and then try again? You can do that from the Permission page of your Google Account: https://myaccount.google.com/permissions

If you're still stuck, can you share the app logs? You can get them from the app's menu > Settings > Logging, then send them by email to dominique@acinq.co . The file you linked in the previous comment does not have enough data.

**Comment by andronoob** [comment]
@dpad85 How could I download old versions of Eclair mobile testnet? I think I might be able to find out a version which is able to switch on GDrive backup, thus provide some clues about this problem.

**Comment by wernert** [comment]
Hi
Same here
I have 2 wallets on different mobile devices with different seeds 
but the same google account.
Both are Eclair mobile mainnet 0.4.9

The first has drive backups enabled and is working since at least April.
android 6

The second just installed gives me the blank screen and access denied 
android 9
drive permission is enabled in app settings
log message:
INFO  f.a.e.w.u.BackupHelper$GoogleDrive  - gdrive sign-in account=null does not have correct permissions, revoking access
ERROR f.a.e.w.a.ChannelsBackupSettingsActivity  - Google Drive sign-in failed, could not get account: com.google.android.gms.common.api.ApiException: 12501:

PS:
Similar effect with the Bitcoin Lightning Wallet

**Comment by andronoob** [comment]
I see that Google tends to remove the App Folder feature

> Support for storing and syncing in the app data folder will likely be removed from Drive in the future. Clients requiring app data storage are strongly encouraged to migrate to a non-Drive solution such as Cloud Firestore.

https://developers.google.com/drive/android/deprecation#accessing_app_data

@dpad85 Is Eclair mobile using this feature?

I have tried to build old versions Eclair mobile by myself. I tried to downgrade the google-related libraries in the dependency tab, but the problem was still there.

I then tried to build the [sample app for GDrive API migration](https://github.com/gsuitedevs/android-samples/tree/master/drive/deprecation), it turned out even this demo could not work at all.

**Comment by andronoob** [comment]
@dpad85 

> Can you remove any access Eclair mobile has to your Google Drive, and then try again? You can do that from the Permission page of your Google Account: https://myaccount.google.com/permissions

I'm really confused. Google Drive settings provided a "Manage Apps" dialog as well. Is this setting related to old backups (seemed to be stored by AppFolder API) only?

I have submitted another issue on this topic (#231).

**Comment by andronoob** [comment]
After upgrading to 0.4.10, I'm currently able to see the consent screen. However, it still failed to enable GDrive backup, the switch was still "off".

**Comment by andronoob** [comment]
I can see the "Eclair Wallet" and "Eclair Wallet Testnet" entries showing in my GDrive settings panel after clicking "allow" button on the consent screen, but, the backup feature still fails to enable.

**Comment by andronoob** [comment]
I have retried several times, by following the enabling steps in Eclair mobile after cancelling permission of Eclair mobile in the GDrive settings panel.

**Comment by andronoob** [comment]
OK, this time I successfully enabled GDrive backup, after setting the Eclair mobile app to connect through my proxy server. If I recalled correctly, this didn't work in the past, however, it's working now.
