### ISSUE TITLE
Did Eclair mobile use GDrive AppFolder for backup?

### ISSUE THREAD

**Issue by andronoob** [ACINQ/eclair-mobile#231]
Google had declaired to [deprecate](https://developers.google.com/drive/android/deprecation#accessing_app_data) the [GDrive AppFolder API](https://developers.google.com/drive/android/appfolder).

I wonder if Eclair mobile once used this feature to backup channel data? If so, will the data still be accessible in the future?

I have checked "Settings" -> "Manage Apps" dialog in my Google drive ( https://drive.google.com/ ), it showed both "Eclair Wallet" and "Eclair Wallet Testnet" in the list, and both items had text like "This app no longer has access to Drive. It is using XXX KB of hidden app data." showed below - in other words, the answer to the first question mentioned above seemed to be "yes".

**Comment by andronoob** [comment]
According to #213, the answers to both questions seemed to be "yes".

**Comment by dpad85** [comment]
Hello,

Versions prior to version 0.4.9 used the hidden `AppFolder` to store channels backup. As you noted this folder will be removed in the future, though AFAICT Google has not given any date yet. In the meantime this folder is still readable by the application.

With 0.4.9 channels backups are saved in a public folder, and not the `AppFolder` anymore. However, when you want to restore a channels backup, the app also reads the `AppFolder`, in case the backup was made before 0.4.9.
