### ISSUE TITLE
Confirmed transaction shows unconfirmed

### ISSUE THREAD

**Issue by lra** [ACINQ/eclair-mobile#237]
I have an on-chain transaction with 1000+ confirmations that still shows as unconfirmed on the Payments page of Eclair.

If I go into the details of the transaction, it shows 0 confirmations. But if I open the TX in the explorer, it shows 1251.

**Comment by dpad85** [comment]
Hi

Can you go to Menu > Network info, and check that your blockheight is
up-to-date ?

If it's not, and your are using a custom electrum server try to connect to
another server.

If it is, scroll down and click on Reset wallet cache. It will resync the
wallet with the blockchain which should take a few minutes.

**Comment by lra** [comment]
> Can you go to Menu > Network info, and check that your blockheight is
up-to-date ?

It is. The other confirmed transactions are fine and go down the list, only this one (which is confirmed everywhere else) is not and stays on top of the list.

> If it is, scroll down and click on Reset wallet cache. It will resync the
wallet with the blockchain which should take a few minutes.

It worked, thanks.
