### ISSUE TITLE
BalanceTooLow$ despite adequate funding

### ISSUE THREAD

**Issue by no-zzz-un** [ACINQ/eclair-mobile#245]
My payments to 3 vendors (bitrefill, satoshis.place, yalls.org) fail immediately with:

> #1 of 1: BalanceTooLow$
> Type: Local

I have two channels, both status normal, both with sufficient "Can send" balances.

update: I've closed those two channels and opened a new one. The problem persists.

![eclair_channels](https://user-images.githubusercontent.com/4035979/82778653-00560180-9e20-11ea-82ae-a5cf549c7646.png)
![eclair_payment_failure](https://user-images.githubusercontent.com/4035979/82778657-021fc500-9e20-11ea-8de9-1e12c58bb1b4.png)

**Comment by AdamISZ** [comment]
I have exactly the same problem. App is up to date (latest version), I tried resetting wallet cache and resetting network database, but made no difference. I have 2 channels, one has sending capacity about 5 times the size of the payment (as reported on the app, and in the log), but above failure is repeatable. Note that this happened today, but I have been using the channel successfully to make 5 or 6 payments over the last week. No idea what changed.

Edit: I should mention that both channels open are acinq nodes, as above. The fact that there are two doesn't seem so relevant (especially given the evidence in the OP).

**Comment by t-bast** [comment]
Sorry I missed this issue. This seems linked to some recent MPP changes.
Could you send me eclair-mobile logs by email (bastien@acinq.fr)?
We have a bunch of important changes coming to the MPP split algorithm (https://github.com/ACINQ/eclair/pull/1427) that should be available in the next eclair-mobile version, but if there are other bugs lurking it would be good to fix them asap.

**Comment by AdamISZ** [comment]
Log sent @t-bast

**Comment by t-bast** [comment]
We recently activated MPP on eclair-mobile, and there is an issue with how the splitting algorithm behaves when you have only a few channels with big(-ish) capacity and send non-negligible amounts to non-neighbour nodes.
We're choosing to deactivate MPP for now (expect a new release of eclair-mobile very soon with that fix) and will re-activate in the next version, with the brand new splitting algorithm that should behave much better.

**Comment by AdamISZ** [comment]
Any update on this? I think I am still getting this same problem, with more than one kind of recipient (including a up to date btcpayserver instance invoice, paying an experimental donation of 1 sat, so pretty clearly 'balance too low' doesn't apply :) ).

**Comment by t-bast** [comment]
This should be fixed with the latest eclair-mobile [release](https://github.com/ACINQ/eclair-mobile/releases/tag/v0.4.12-MAINNET) that temporarily disables splitting multipart payments.
The next release will provide the new splitting algorithm (available on eclair-core master).

**Comment by AdamISZ** [comment]
Yeah sorry deleted my comment when i realised there was an update. And it works :+1:

**Comment by t-bast** [comment]
Great, good to know!

**Comment by AdamISZ** [comment]
I think I may have spoken too soon in saying this is resolved. I just did a trivial test payment to a btcpayserver instance before my message above ("it works"), but I have since found that every attempt to pay bitrefill has failed (I guess 6 or so attempts over the last several days), interestingly each attempt (amounts are far below the channel balance) has as the *first* of its ten failures an "insufficient funds: missing = Satoshi(X) ...", and all the remaining failures say channel unavailable or disabled.

**Comment by t-bast** [comment]
Hey @AdamISZ, this indicates an issue either with the state of the channels, with the routing DB or with how we manage retries.
Could you send me your eclair logs for some of those payment attempts?

**Comment by t-bast** [comment]
In the channels tab, everything looks right? All the channels indicate a `NORMAL` state?

**Comment by AdamISZ** [comment]
Yes channels are normal state, 2 channels one a bit smaller than the required amount (afair) the other very much larger.

**Comment by t-bast** [comment]
I'm suspecting an issue with how channel balances are propagated throughout the app, I'll check exactly what commit of `eclair-core` the latest `eclair-mobile` version uses.
If you could send me some logs that would be helpful!

**Comment by AdamISZ** [comment]
Sent
