### ISSUE TITLE
Unusual formula for measuring the fee rate mismatch

### ISSUE THREAD

**Issue by canndrew** [ACINQ/eclair-mobile#246]
The formula eclair uses for calculating the difference between two fee rates is:

```
  /**
   * @param referenceFeePerKw reference fee rate per kiloweight
   * @param currentFeePerKw   current fee rate per kiloweight
   * @return the "normalized" difference between i.e local and remote fee rate: |reference - current| / avg(current, reference)
   */
  def feeRateMismatch(referenceFeePerKw: Long, currentFeePerKw: Long): Double =
    Math.abs((2.0 * (referenceFeePerKw - currentFeePerKw)) / (currentFeePerKw + referenceFeePerKw))
```

This seems a bit odd to me. If the reference fee rate is `1btc` and the current fee rate is `0.0001btc` then the average of the two will be (approximately) `0.5btc` - which is half the reference fee rate but 500 times the current fee rate. It would make more sense to measure this on a log scale so that an infinite difference (in terms of orders-of-magnitude) becomes an infinite `feeRateMismatch`, rather than a `feeRateMismatch` of 2.

Is it worth changing the formula to `|log(reference) - log(current)|`? (And also changing the name of the config option to avoid silently changing its meaning?)

**Comment by t-bast** [comment]
Could you please port this issue to https://github.com/ACINQ/eclair instead? This isn't specific to eclair-mobile, this is really in eclair-core.

**Comment by canndrew** [comment]
Oops, sorry. I've ported the issue here: https://github.com/ACINQ/eclair/issues/1438
