### ISSUE TITLE
DNS recovery not working

### ISSUE THREAD

**Issue by SneezyDwarf111** [ACINQ/eclair-mobile#247]
I had some lightning channels 2 years ago that were never force-closed. I tried re-installing the app/phone, restarting app, using eclair-DNS trick, and every combination of these. Nothing worked.

The first time I did the DNS trick, I think it started working. New transactions populated, but they disappeared.

But now when I try the DNS trick again, EClair tries syncing from electrum.acinq.co:50002, which I think is the normal server and not the recovery server... I still get the DNS approval message at http://eclair.dns so I thought the server may be down?

Any advice is appreciated!

**Comment by sstone** [comment]
DNS recovery does work, but it is specific to eclair-mobile 0.3.0. I'll reply to you on gitter and close this issue (we use only github for code and technical issues, and gitter for support).
