### ISSUE TITLE
Custom electrum server as a Hidden Service not working

### ISSUE THREAD

**Issue by ghost** [ACINQ/eclair-mobile#249]
As described in the subject.
My custom electrum service is listening on a hidden Tor service at port 50001. I am using Eclair via Orbot VPN

**Comment by ghost** [comment]
How to reproduce:
- Install Orbot
- Add eclair to the list of VPN apps
- Enable orbot VPN
- In Eclair, put a custom electrum server as a .onion address
- The electrum server (.onion address) is not using any TLS encryption
- Eclair fails to connect to the electrum.

**Comment by ghost** [comment]
I suspect it needs a valid certificate on electrum? This is not doable with .onion addresses

**Comment by t-bast** [comment]
It should not require a valid TLS certificate if you're using port 50001, that case should work.

- Can you share the exact url you're setting in eclair-mobile (please redact the onion part for privacy)?
- What version of eclair-mobile are you using?
- Can you have a look at your logs and search for warnings/errors?

**Comment by t-bast** [comment]
Are you explicitly specifying port 50001 when you're setting the electrum url in eclair-mobile? If you're not that's probably the issue.

**Comment by ghost** [comment]
I am using something like 

```addresss.onion:50001```

where address is a Tor V3 hidden service

**Comment by ghost** [comment]
Eclair Mobile v0.4.11

**Comment by ghost** [comment]
I looked at the logs and the issue confirms what I was saying before: ```NotSslRecordException``` when trying to connect to my server

**Comment by ghost** [comment]
Last thing, the exactly same setup, with Orbot VPN and my tor v3 electrum server works as a backend for the BlueWallet

**Comment by t-bast** [comment]
That's weird, @dpad85 shouldn't this work on eclair-mobile 0.4.11?

**Comment by dpad85** [comment]
I'll have to check that, indeed certificate should be ignored for this
address on 0.4.11.

In any case the embedded Tor support will have to be backported from
Phoenix, that will solve the problem and make using Tor easier on eclair
mobile.

**Comment by ghost** [comment]
> embedded Tor support will have to be backported from Phoenix

That'd be really great!
