### ISSUE TITLE
HELP PLZ!!!! 

### ISSUE THREAD

**Issue by ROBKEN2014** [ACINQ/eclair-mobile#25]
How can I request a lightning payment? I want to receive from a friend, I have no idea how to create a request. I'm already connected to ACINQ's lightning network.

**Comment by sstone** [comment]
You cannot receive payments with our mobile node (see our [FAQ](https://github.com/ACINQ/eclair-wallet/wiki/FAQ), but you can with our "regular node" (checkout [eclair](https://github.com/ACINQ/eclair)).
