### ISSUE TITLE
[request] method to migrate existing channel to a new device

### ISSUE THREAD

**Issue by brianddk** [ACINQ/eclair-mobile#251]
I have an old phone with GDrive backup enabled and functioning.  I have full access to my correct seed.  I want to move my Eclair wallet to a new phone as part of a handset upgrade, but previous discussions (November) imply that the only migration path is to close the channel then move use the seed to access the on-chain funds.

Shouldn't the GDrive backup provide some way to migrate the channel data as well, or is there some fundamental technical hurdle I'm missing here?

**Comment by dpad85** [comment]
Hello,

You can move the channels from one device to another using the backup. However please note that:

- if you open the app simultaneously on the old device and the new device, with the channels loaded on both, these channels will conflict and close. So make sure the app on the old device is off when you restore on the new device. Once you've completed the restore process on the new device and checked that everything is nominal, you can safely uninstall the app on the old phone.

- when you restore the seed on your new device, you'll land [on the screen for restoring the channels backup](https://user-images.githubusercontent.com/5765435/86150448-b1297d80-bafd-11ea-953a-b09922e33d3e.png). Check that the number of channels and the timestamp is consistent with what you would expect. If you restore an old backup with revoked state, your peer may close the channels.


> imply that the only migration path is to close the channel then move use the seed to access the on-chain funds.

It's not the only path, but it's foolproof. Restoring on-chain funds is very simple, for restoring channels you have to be a bit more careful.

**Comment by brianddk** [comment]
@dpad85 , Thank you for the info.

Closing
