### ISSUE TITLE
Payment attempt failed

### ISSUE THREAD

**Issue by anthony-ism** [ACINQ/eclair-mobile#26]
Attempt to make payment to blockstream store using random eclair node. Get the following message

![screenshot_20180407-143041](https://user-images.githubusercontent.com/5731861/38458840-84f025da-3a70-11e8-8e7d-28b7ded49345.png)

Attempted a few times and also unchecked uncapped fees preference.

Each time I try I keep getting the same node offline. Basically no route to host?

Also I attempted to open a channel directly to the blockstream store and the channel never successfully opened, and I forced closed it and my funds are in limbo.  (Not concerned about that I read the FAQ ;) )

Suggestions are welcome to complete this transactions.

**Comment by anthony-ism** [comment]
Also it would be useful to be able to easily retry for payments that have failed. Right now I need to dig into the details, find the payment hash, copy it, and repeat the process.

**Comment by sstone** [comment]
This is very likely a liquidity problem (see our [FAQ](https://github.com/ACINQ/eclair-wallet/wiki/FAQ#why-does-my-5-payment-to-ln-shops-fails-while-my-1-payments-to-eg-yalls-work)). Basically most channels are small and very few of them can handle a "largish" payment of $30 (you should be able to pay very cheap items on yalls for example). It will get better as the network grows.
