### ISSUE TITLE
Receive problem

### ISSUE THREAD

**Issue by Davidacropros** [ACINQ/eclair-mobile#268]
Hi, I've juste sent some USDT from my kraken account (Omni method) to my Eclair Wallet and I did not realized I could only send BTC. The transaction is completed and I do not know how to recover the amount sent. Do you convert it in BTC ? is there a way to send it back to my Kraken account ? Sorry for this stupid mistake but I need help, the transaction is 1695USDT I hope to recover. Thanks for your help.

**Comment by t-bast** [comment]
I think you should contact Kraken support, we have absolutely no support for USDT so that scenario doesn't make any sense.
If Kraken sent bitcoin to your eclair-mobile then you should receive them. Otherwise it's simply not possible to send something that's not bitcoin to eclair-mobile.

There's nothing that can be done on the eclair-mobile side AFAIK.

**Comment by Davidacropros** [comment]
Thanks for your fast answer

**Comment by Davidacropros** [comment]
Hi, Kraken support said the transaction is successfull (see transaction here : https://omniexplorer.info/tx/2335390fe46ddf792f4d88129c53b8c1510e65bbc6890b99defefd0f8d9813c2)

They can not do anything at this point, can you credit the equivalent value in BTC to my wallet ?

**Comment by t-bast** [comment]
I don't understand, I think you're misunderstanding what eclair-mobile does. This is not an exchange, we're never in control of any of your funds, this is a non-custodial wallet. We cannot "credit" anything nor have we received any of your bitcoin.

I don't know the details of how USDT work, but it looks like a normal bitcoin transaction was made to your address: https://blockstream.info/address/36RLEy9NXPz1Phmfg4dNyhjuE3fSmmyLTJ

So it should show in your eclair-mobile wallet (if that address was indeed generated from your eclair-mobile).

**Comment by Davidacropros** [comment]
Yes, I've recieved 0.0000273 BTC so it is far from what I've sent (1695USDT = 0.03BTC)

**Comment by t-bast** [comment]
Well that's what the transaction you linked (https://blockstream.info/tx/2335390fe46ddf792f4d88129c53b8c1510e65bbc6890b99defefd0f8d9813c2) sent to your address.

If more should have been sent, that's something you need to ask the sender (Kraken). With the data you're providing everything looks correct from eclair-mobile's point of view. The missing funds don't seem to be bitcoins so we cannot do anything about it...

**Comment by Davidacropros** [comment]
Ok but were are the missing funds ? 
here we can clearly see "Simple Send 1,695.00 TetherUS" : https://omniexplorer.info/address/36RLEy9NXPz1Phmfg4dNyhjuE3fSmmyLTJ
And the result on my wallet is 0.0000273 BTC.
I know I've made a mistake but the transaction appear successful, why is there so much less left in my wallet ?

**Comment by t-bast** [comment]
> Ok but were are the missing funds ?

I have no idea, that is something you should ask the people behind that omni system (or Kraken).
It's not on the bitcoin blockchain nor in lightning, so there's nothing we can do.

**Comment by Davidacropros** [comment]
Ok, how can i get my private key wallet ?

**Comment by dpad85** [comment]
> Ok, how can i get my private key wallet ?

Eclair mobile will not display your seed/private key. But you can restore your [12/24 words seed backup into Electrum](https://github.com/ACINQ/eclair-mobile/wiki/FAQ#can-i-restore-my-seed-on-another-bitcoin-wallet-), then use Electrum to generate your private keys. 

Note that if you used a passphrase when you created your wallet, you need to enter the exact same passphrase (case sensitive) in electrum (in the restore screen, options > extends this seed with custom words).

**Comment by Davidacropros** [comment]
Ok I've restored my wallet on electrum using the seeds, now how can I generate private key ? 
When I try to export private keys, there is a list of 31 addresses

**Comment by Davidacropros** [comment]
HI again,
I found that Tether uses the Omni Protocol which is based on Bitcoin and has the same address format with Bitcoin. Because of that, it is possible to send USDT to a Bitcoin address by mistake.
So it is technically possible to recover USDT sent to a Bitcoin address by mistake. For this I need my private key to import it into a omni wallet. 
I tried import my Eclair Wallet in Electrum using the 12 words, tick the BIP39 checkbox, and then select BIP49. None of the USDT are shown on Electrum Wallet (offline), juste some little BTC (0.0000273) witch came with the transaction (don't know why).

But I can see USDT from my Omni account (read only address) AND by simply checking the address on Omni website : https://www.omniwallet.org/
Eclair address : 36RLEy9NXPz1Phmfg4dNyhjuE3fSmmyLTJ

I tried to export private keys from Electrum but I get about 31 addresses (and private keys) included the one I sent USDT to but none of them has USDT on it.

I dont know how to recover those USDT, my knowledge is really basic and I’m not sure of all I try and read... I start to be afraid to never get back this money (about 1700usdt).

Please help me.
Thank you

**Comment by pm47** [comment]
Open Electrum, go to the Addresses tab, select the line with your address, right click, "private key".

That is the private key that you are looking for (do not share it with anyone).

**Comment by Davidacropros** [comment]
Yes, I already done this, none of the USDT are shown on this address on Electrum neither when I import this private key in Omni wallet. I can juste see USDT from my Omni account (imported read only address) AND by checking the address on Omni website : https://www.omniwallet.org/ With destination address : 36RLEy9NXPz1Phmfg4dNyhjuE3fSmmyLTJ

Maybe I did not imported correctly the Eclair address on Electrum ?
I choosed "I already have a seed", pasted them 12 words, tick the BIP39 checkbox, and then select BIP49. Is there any other septs ? Witch are the 30 other addresses I see on Electrum ? 

Sorry, I understand this is a little out of your job to assist me on this problem as it is not related to Eclair wallet but I really need some advise and explanation to get this thing right. Hope you understood the problem and have some wise advise.

**Comment by Davidacropros** [comment]
Et si quelqu'un parle français ça peut clairement m'aider.

**Comment by pm47** [comment]
Vous avez fait ça ?

![screenshot](https://user-images.githubusercontent.com/2028222/115027669-48609580-9ec4-11eb-8beb-0b8bf48c09e6.png)

**Comment by Davidacropros** [comment]
Oui exactement ! mais rien n'est visible. Il n'y a qu'en ajoutant une adresse en lecture seule que je vois les fameux USDT.
![screencapture-omniwallet-org-wallet-addresses-2021-04-16-15_00_14](https://user-images.githubusercontent.com/82596293/115028050-ba38df00-9ec4-11eb-9385-eddd026b2942.png)

**Comment by pm47** [comment]
C'est que vous vous êtes trompé dans l'import de la clé privée, je ne vois pas l'adresse 36RLEy9NXPz1Phmfg4dNyhjuE3fSmmyLTJ dans la liste Dépensable. Vous avez visiblement importé les clés privées qui correspondent à d'autres adresses.

**Comment by Davidacropros** [comment]
Pourtant j'ai bien pris la clé privée correspondant à 36RLEy9NXPz1Phmfg4dNyhjuE3fSmmyLTJ sur mon export de Electrum, et lorsque je l'import sur Omni ça me sort une autre adresse qui n'a rien a voir (ni est présente nul part dans mon export). 
J'ai tout supprimé et re-importé la clé privé et toujours le même soucis : 
![Capture d’écran 2021-04-16 à 15 40 30](https://user-images.githubusercontent.com/82596293/115033079-4b5e8480-9eca-11eb-814c-a216c51be89a.png)

**Comment by pm47** [comment]
Ok je crois que je vois, omniwallet importe une adresse p2pkh (qui commence par 1) alors que vous avez une adresse p2sh-p2wpkh (qui commence par 3). Les deux correspondent à la même clé privée.

Tout cela ne concerne pas du tout Eclair Mobile, je ferme ce ticket et il faut que vous alliez voir https://github.com/OmniLayer/omniwallet.

D'ailleurs leur wiki contient une page précisément là dessus :
https://github.com/OmniLayer/omniwallet/wiki/Recovering-funds-from-a-Segwit-Address

Tant que vous avez la clé privée, les fonds ne sont pas perdus, même s'ils peuvent être difficiles à récupérer. Bonne chance
