### ISSUE TITLE
Price rate API returns 404

### ISSUE THREAD

**Issue by raymond-w-ko** [ACINQ/eclair-mobile#279]
Hi,

I think `blockchain.info` changed their API, since fiat price of BTC is not working properly in the app.
https://github.com/ACINQ/eclair-mobile/blob/e8daa4cc84ed99da459731b5cec3d65a3e6d2067/app/src/main/java/fr/acinq/eclair/wallet/utils/Constants.java#L181

I think they changed it to: `https://blockchain.info/ticker` as documented here:
https://www.blockchain.com/api/exchange_rates_api

**Comment by dpad85** [comment]
Thanks for reporting the issue, will fix!
