### ISSUE TITLE
iOS version?

### ISSUE THREAD

**Issue by ghost** [ACINQ/eclair-mobile#282]
Sorry if this is the wrong place for this, but will an iOS version be made?

**Comment by sstone** [comment]
No there won't be an iOS version, you should use [Phoenix](https://phoenix.acinq.co/) instead.

**Comment by ghost** [comment]
I cannot open my own channels with phoenix though.

**Comment by sstone** [comment]
That is correct. You can read more about the choices we made for Phoenix on there: https://medium.com/@ACINQ/introducing-phoenix-5c5cc76c7f9e
In a nutshell, connecting to the LN network through our node (which is probably the most reliable LN node by a fair margin) allows us to provide users with a UX that is almost as seamless as what you get with a custodial wallet (instant channels, trampoline routing, encrypted peer backups, on-demand channel creation, ...).

**Comment by ghost** [comment]
Thank you for your reply, I'll read that. 
Still disappointing there isn't an option for iOS which gives you the control I want.
