### ISSUE TITLE
Fund Recovery Help

### ISSUE THREAD

**Issue by JEA1310** [ACINQ/eclair-mobile#283]
Good day I was sent here via Email for help with recovering funds in a closed channel. I had changed phones and recovered the account which lead to closing the channel, but it now consistently states "Err-Information_Leak". The application states through notification that I will receive funds in 720 blocks; repeatedly to no avail. Any help with this issue would be greatly appreciated.

**Comment by dpad85** [comment]
> I had changed phones and recovered the account which lead to closing the channel

Did you run both apps simultaneously ? If so, channels will conflict and force close.
What's your node id?

**Comment by JEA1310** [comment]
Thank you so much for the reply and no I no longer have the other phone (I can get it in a month otherwise) nor the phone number (it's gone). I transferred successfully and my Peer Node ID is 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f

**Comment by JEA1310** [comment]
> > I had changed phones and recovered the account which lead to closing the channel
> 
> Did you run both apps simultaneously ? If so, channels will conflict and force close. What's your node id?

Sorry I'm new I guess I needed to quote reply you.

**Comment by JEA1310** [comment]
> > I had changed phones and recovered the account which lead to closing the channel
> 
> Did you run both apps simultaneously ? If so, channels will conflict and force close. What's your node id?

Hello I referenced my node ID is there other information I need or what may be next for me?

**Comment by dpad85** [comment]
> my Peer Node ID is 03864ef02...

That's the ID of your peer which is not what we need. Can you send your logs by email to dominique@acinq.co (to do that, Menu > Settings > Logging > share logs).

**Comment by dpad85** [comment]
Closing this issue as it was done by email.
