### ISSUE TITLE
open channel fees too high

### ISSUE THREAD

**Issue by fjcalderons** [ACINQ/eclair-mobile#3]
First of all, congratulations to all the team!!! today is another great day with this release :smile: 

I have 218047 sats (14,82 USD) on my eclair btc address, when I try to open a channel it only let me to open the channel with 118000 sats (8 USD), in other case I get a "not enough funds" message, why is that? this means that the chain opening channel fee it's going to be of 6+ USD?

![screenshot_20180404-163625](https://user-images.githubusercontent.com/25903483/38330662-8f191396-3827-11e8-9118-a436455f61e8.png)

**Comment by matthewjamesr** [comment]
@fjcalderons I am just a bystander, but what should an average channel opening fee be? What have you seen? I am currious.

**Comment by fjcalderons** [comment]
@matthewjamesr one hour ago I just opened a channel on my mainnet node (not the eclair wallet), the capacity of that channel is 330000 satoshis (~22 USD) and the commit fee was 724 satoshis (~0.05 USD), so I think opening channels on eclair wallet should be something like that.

**Comment by dpad85** [comment]
Hi, thanks for reporting the issue!

This issue is the same as #6 : a 1 mBTC leftover was required to handle the tx fee, that's why you are limited to a 118000 sat channel. This control is obsolete and will be removed by PR #11 

@matthewjamesr Channel funding tx fees can be customised by the user

**Comment by fjcalderons** [comment]
@dpad85 perfect, we'll wait for the new release :smile: 

closing
