### ISSUE TITLE
Testnet wallet: "Seed is unreadable. Aborting"

### ISSUE THREAD

**Issue by DanielWeigl** [ACINQ/eclair-mobile#32]
I had the testnet wallet installed and already used it a few times. Just wanted to buy a blockachino again but now I get this message:
![image](https://user-images.githubusercontent.com/1370302/38559288-ed569744-3cd2-11e8-9d83-b7be07620717.png)

Tried:
 - start with old data -> as above
 - uninstall / reinstall testnet wallet -> same
 - delete app-data and app-cache, and uninstall / reinstall testnet wallet -> same

In the meantime I have the prodnetwallet also installed - might there be an overlap of the data storage?

Testnet wallet: v0.2.5

**Comment by dpad85** [comment]
What version of android are you using, and what model is your phone? Also, is your phone rooted?

> In the meantime I have the prodnetwallet also installed - might there be an overlap of the data storage?

No it's not possible since the 2 apps have different ids, and different storages isolated from one another.

**Comment by vmeoc** [comment]
Hi,
Had the same issue.
Tried delete app-data and app-cache, and uninstall / reinstall testnet wallet and it worked for me.
Testnet wallet: v0.2.5
Android 7

**Comment by DanielWeigl** [comment]
Just tried once again (deleting data&cache, deinst and install again), still same error.

Phone: OnePlus5 with stock OS (Android 8.0.0, non Root)

The ADB logoutput is also not very verbose:

```
04-12 09:42:34.064  1423  2760 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=fr.acinq.eclair.wallet/.activities.StartupActivity bnds=[670,1368][858,1583] (has extras)} from uid 10137 pid 3603
04-12 09:42:34.083  3603  3603 D AppTracker: App Event: stop
```

The installed applicationIds:
```
OnePlus5:/ $ pm list packages | grep eclair                                                                                                                                                 
package:fr.acinq.eclair.wallet
package:fr.acinq.eclair.wallet.mainnet
```

**Comment by dpad85** [comment]
@DanielWeigl Could you install this apk: https://acinq.co/assets/wallet/eclair-wallet-0.2.5-TESTNET-issue32.apk ? This version simply adds a log in startup to help with debugging.

* then run this command: `adb -d logcat StartupActivity:d *:S` - you should get an exception with more details.

* you can also check the unreadable seed by backuping the application's data with the `adb backup -apk fr.acinq.eclair.wallet` command. Then use [this utility](https://github.com/nelenkov/android-backup-extractor/releases) to extract the backup content (run `java -jar abe-all.jar unpack backup.ab backup.tar <password>`)

Open the resulting tar file, and go to `apps/fr.acinq.eclair.wallet/f/eclair-wallet-data` and extract the seed.dat file. Could you paste it somewhere so we can take a look at it?

**Comment by DanielWeigl** [comment]
This version started correctly and presented me the "Import Existing wallet / Create new Wallet" activity.

```
adb -d logcat StartupActivity:d \*:S
04-12 14:39:01.714 26379 26379 D StartupActivity: last used version = 0
04-12 14:39:01.714 26379 26379 D StartupActivity: has eclair started once ? false
04-12 14:39:01.714 26379 26379 D StartupActivity: fresh install ? true
```
if i deinstall this one and reinstall the version from the playstore again, its again showing me the error "Seed is unreadable" on startup

Starting the issue32-apk after starting the playstore-apk once (and got stuck on bug message, without clearing data) also results in:
```
04-12 14:44:03.836 27699 27699 D StartupActivity: last used version = 0
04-12 14:44:03.836 27699 27699 D StartupActivity: has eclair started once ? false
04-12 14:44:03.836 27699 27699 D StartupActivity: fresh install ? true
```

Anyway - bug (whatever it is), seems to be fixed in the apk you provided me

**Comment by dpad85** [comment]
It seems that, with the version from the playstore, deinstalling the application does not completely clean the app data layout, and the eclair data directory remains. When starting, eclair-wallet checks this directory existence and, finding it, suppose that the seed exists, which is not the case. Logically, when it actually tries to read the seed, it fails with the `unreadable` error.

The diff between the playstore version and the version I gave you is one log, so it could not solve any bug by itself.

I think that there is in fact two issues here:
* android may not completely clean the app data
* eclair-wallet v0.2.5 checks are not thorough enough. Luckily, eclair-wallet checks in v0.3+ are more strict and this should not happen again.

Thanks for your help!
