### ISSUE TITLE
Eclair Mobile app can't pay yalls comments articles.

### ISSUE THREAD

**Issue by dpad85** [ACINQ/eclair-mobile#41]
<a href="https://github.com/bitcoinuser"><img src="https://avatars1.githubusercontent.com/u/1178856?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bitcoinuser](https://github.com/bitcoinuser)**
_Wednesday Mar 21, 2018 at 16:30 GMT_
_Originally opened as https://github.com/ACINQ/eclair/issues/499_

----

Hi, I can pay yalls articles, but when I try to pay to comment on yalls articles, doesn't work.

![1c8ac742-c972-49fe-b4e1-932644603a3f](https://user-images.githubusercontent.com/1178856/37722994-08cb7c28-2d0c-11e8-9b46-634baf653484.jpeg)

**Comment by dpad85** [comment]
<a href="https://github.com/dpad85"><img src="https://avatars3.githubusercontent.com/u/5765435?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dpad85](https://github.com/dpad85)**
_Wednesday Mar 21, 2018 at 16:42 GMT_

----

Hi, i managed to pay an article on Yalls, and also to add a comment. Are you sure you did not change the amount when paying?

You can check that if you click on the failed payment:
* amount requested, which is the value asked by Yalls for the comment
* amount sent, which is the amount you attempted to send

If the amount sent is lower (or 2 times greater) than the amount that was requested, the Yalls node will fail the payment. 

This might also be an issue on Yalls side (this is a `RemoteFailure`, which means that the payment was failed by the remote Yalls node).

**Comment by dpad85** [comment]
<a href="https://github.com/bitcoinuser"><img src="https://avatars1.githubusercontent.com/u/1178856?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bitcoinuser](https://github.com/bitcoinuser)**
_Wednesday Mar 21, 2018 at 16:48 GMT_

----

1- I'm sure I don't change the amount value.
2- The value that appear on yalls is in dollar. So Is not possible to know the value requested in btc

**Comment by dpad85** [comment]
<a href="https://github.com/dpad85"><img src="https://avatars3.githubusercontent.com/u/5765435?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dpad85](https://github.com/dpad85)**
_Wednesday Mar 21, 2018 at 18:03 GMT_

----

Could you paste the payment request here?

**Comment by dpad85** [comment]
<a href="https://github.com/bitcoinuser"><img src="https://avatars1.githubusercontent.com/u/1178856?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bitcoinuser](https://github.com/bitcoinuser)**
_Wednesday Mar 21, 2018 at 18:06 GMT_

----

lntb210n1pdt98c8pp542e6tnq5w52grhzsgengddlt0m6z3ak3kd2ycgl2rlx88mfztv8qdq4g9jxggrpyp3k7mtdv4h8gcqzysdr4ng7452kxaqwmsrwcgdfgglfmx5f67dymj65q24d9ut9r70qr8cc284v2ljs7hd97p5tt0ek6x53d80ug25k7jrzuj6evlrjxnfaqpetsz4x

**Comment by dpad85** [comment]
<a href="https://github.com/bitcoinuser"><img src="https://avatars1.githubusercontent.com/u/1178856?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bitcoinuser](https://github.com/bitcoinuser)**
_Wednesday Mar 21, 2018 at 18:07 GMT_

----

![captura de tela de 2018-03-21 15-06-55](https://user-images.githubusercontent.com/1178856/37728616-88a1a104-2d19-11e8-9424-2e73e719e60d.png)

**Comment by dpad85** [comment]
<a href="https://github.com/ric2b"><img src="https://avatars3.githubusercontent.com/u/8846579?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ric2b](https://github.com/ric2b)**
_Wednesday Mar 21, 2018 at 18:29 GMT_

----

I also can't reproduce, everything worked on my end.
I was even able to pay by scanning the QR code on your image :p 
(only once, it now complains that it has already been paid)

**Comment by dpad85** [comment]
<a href="https://github.com/bitcoinuser"><img src="https://avatars1.githubusercontent.com/u/1178856?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bitcoinuser](https://github.com/bitcoinuser)**
_Wednesday Mar 21, 2018 at 18:32 GMT_

----

Very strange.

**Comment by dpad85** [comment]
<a href="https://github.com/bitcoinuser"><img src="https://avatars1.githubusercontent.com/u/1178856?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bitcoinuser](https://github.com/bitcoinuser)**
_Wednesday Mar 21, 2018 at 18:34 GMT_

----

Please, open only one channel with yalls: 039cc950286a8fa99218283d1adc2456e0d5e81be558da77dd6e85ba9a1fff5ad3@34.200.252.146

And try to pay this: 

lntb1500n1pdt9fv7pp5ul4qz8pdydjdkuzcuxealzqguyruutc9r7qge04hzqkyp5lumfyqdpa2fjkzepqg9e8g6trd3jn5gzhdpshggrhda6kcepqdpshqur9dcsxje3w9chq6cqzys66qwmrwhajhaxvp385u0ht3k4ue8rpxt3r7svcxc2tt65kswhrukdf5xg6l0pm4gvgpwgv0w048h80wh59y6gtwrnthg6vhmd69d77gpe4rky0

**Comment by Perlover** [comment]
I cannot pay too
But i think that Yalls has testnet node DB on mainnet node...

**Comment by sstone** [comment]
I just tried with https://mainnet.yalls.org from eclair-wallet 0.3.1, without a direct channel to the yalls node (I just have channels to our ACINQ node), and it worked.

There are 2 yalls sites (one on testnet, one on mainnet), and eclair can only pay payment requests that are on the same chain. You can tell by the prefix of the payment request:

- lnbc for mainnet
- lntb for testnet 
 
The error that you see when you try to pay a payment request that not on the same chain is not specific enough, we'll display a better error message.
