### ISSUE TITLE
Feature Request: Request payment via lightning in Android App

### ISSUE THREAD

**Issue by dpad85** [ACINQ/eclair-mobile#48]
<a href="https://github.com/PRabahy"><img src="https://avatars2.githubusercontent.com/u/429961?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [PRabahy](https://github.com/PRabahy)**
_Wednesday Dec 20, 2017 at 04:22 GMT_
_Originally opened as https://github.com/ACINQ/eclair/issues/302_

----

I couldn't find a way in the android app to request tBitcoin via lightning. If I swipe left, it gives me a traditional address and QR code, but that requires a transaction on the blockchain.

**Comment by dpad85** [comment]
<a href="https://github.com/sstone"><img src="https://avatars3.githubusercontent.com/u/1573866?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sstone](https://github.com/sstone)**
_Wednesday Dec 20, 2017 at 09:25 GMT_

----

This is by design, for now the mobile app can only pay on LN, which makes it safe to use even if the phone is offline most of the time. Receiving payments is on our roadmap but we'll need to deploy our monitoring solution first. There is a more detailed explanation [there](https://medium.com/@ACINQ/announcing-eclair-wallet-a8d8c136fc7e) but the gist of it is that to receive LN payments you need to monitor the blockchain, detect cheating attempts and react. This would be difficult on a device that is often offline, but can be delegated to a third-party watcher without loss of privacy and very little trust.

**Comment by dpad85** [comment]
<a href="https://github.com/Sgt-Miller"><img src="https://avatars3.githubusercontent.com/u/17806210?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Sgt-Miller](https://github.com/Sgt-Miller)**
_Wednesday Dec 20, 2017 at 11:33 GMT_

----

For more info refer point 3 here :
https://github.com/lightningnetwork/lightning-rfc/blob/master/05-onchain.md

**Comment by nilskp** [comment]
I would imagine most people have their phones on most of the time. Wouldn't it make sense to have built-in monitoring?

**Comment by Kixunil** [comment]
@nilskp monitoring requires scanning whole blockchain, so that'd be essentially like running a full node. The battery would be dead very quickly and carrier fees probably unacceptable for most people.

**Comment by alexk111** [comment]
Have you seen @bluewallet's LndHub? http://lndhub.io/about It looks like a solution for this.

**Comment by molxyz** [comment]
@alexk111 
> Have you seen @BlueWallet's LndHub? http://lndhub.io/about It looks like a solution for this.

It's a custodial wallet. Your coins are owned by someone else, they can wait until many people put in lots of coins in there, and they disappear, it's called "exit scam".  Eclair mobile wallet is not custodial, much better for you because you are in control of your coins, and Eclair is a no brainer wallet, very easy to use and manage.

**Comment by alexk111** [comment]
@molxyz Their open-source LndHub is a solution for that issue. You can host your own LndHub on a server and connect your wallet to it. In that case your lightning node runs on a machine under your control and your mobile wallet doesn't have to be always online.

**Comment by molxyz** [comment]
@alexk111 
Thanks but no thanks :-)  It's better you get the code from its origin, not from a second or third party. I have been running LND on my server since day one when LND alpha was just released, so it's been over two years now, you can do this too, get it from source and here's the guide:  https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md

**Comment by alexk111** [comment]
@molxyz And Eclair wallet on your mobile phone connects to LND on your server?

**Comment by molxyz** [comment]
@alexk111  Yes, you can use Eclair mobile to connect and open channels to your LND node or c-lightning node.  But we're getting offtopic here. This is Eclair repo, you should not use it to advertise something else out of respect and courtesy for Eclair developers. 

EDIT: And btw, if you were talking about the "payment request" feature for Eclair mobile, it is coming:  https://twitter.com/acinq_co/status/1093985988215492608

**Comment by alexk111** [comment]
@molxyz Yeah, I meant using Eclair mobile as a "thin client" for lnd node, to be able to request payments from a mobile phone. Thanks for the link to their tweet! Can't wait to try it :)

**Comment by nilskp** [comment]
It's not clear to me how this commit fixes this issue.

 https://github.com/ACINQ/eclair-mobile/commit/80258c38d03c75cc1e96ffc56d8a373eafc66832

**Comment by dpad85** [comment]
Hi @nilskp 

The https://github.com/ACINQ/eclair-mobile/commit/80258c38d03c75cc1e96ffc56d8a373eafc66832 commit is the `v0.4.0` release commit. This version contains the code enabling the creation of lightning payment requests with the app, and the reception of payments over Lightning. The code itself is scattered over [several commits](https://github.com/ACINQ/eclair-mobile/compare/v0.3.19-TESTNET...v0.4.0-TESTNET).

You can find more information here: https://github.com/ACINQ/eclair-mobile/releases/tag/v0.4.0-TESTNET
