### ISSUE TITLE
Wallet could not find a path to the payee

### ISSUE THREAD

**Issue by charltonh** [ACINQ/eclair-mobile#55]
I've been playing with the eclair wallet (mainnet) and have opened a channel to bitrefill. I have tested payments to bitrefill and it works. However I cannot pay yalls.org even $0.01 because of a payment routing error. How can this be the case when they are directly connected with a relatively large capacity channel?

The error I'm getting specifically is: "The wallet could not find a path to the payee"

Does anyone know what's going on here?  I know I can try my luck and open more channels, but it seems like there is no reason why such a simple route would fail.

**Comment by irekzielinski** [comment]
Also having quite a low success rate. Tried few channels including Blockstream, Federal Reserve.
Mostly doing tiny donations, yalls articles, etc. Often few payments will be successful, bit then all subsequent ones will either fail or be pending for a long time.
Would be great to have a low level log for each payment accessible from the app - so we can see what's going on.

**Comment by sstone** [comment]
We are working on improving user feedback but often there is not much more that eclair can tell when there is a routing error. Still, when a payment fails you see the number of attempts your wallet made, and a list of all errors returned by the nodes that were unable to forward the payment.
It is usually a liquidity issue: most channels are tiny and get depleted very quickly. This will get better as the network grows. 
It could also be a temporary problem with a node on the route, again this  will get better as the network grows and nodes become more reliable.

**Comment by charltonh** [comment]
> Still, when a payment fails you see the number of attempts your wallet made, and a list of all errors returned by the nodes that were unable to forward the payment.

I wish this was the case, as there is only one attempt made and no additional info, only "The wallet could not find a path to the payee".  No node info or which node couldn't forward the payment either.  It would be nice if it would mention that and if it could find a route maybe indicate that the funds have been depleted along that route or some other piece of useful information.

In this case I'm pretty sure it's not a liquidity issue as I mentioned in the initial report, I located the path and the channels on #recksplorer.  In addition I now have two channels open which are connected, one with only one hop (bitrefill -> yalls).  The payment is only $0.01 (1.5 bits).

I am able to reproduce this, so let me know if there's anything I can provide.

**Comment by irekzielinski** [comment]
I had much better success with small payments (below 1USD) when connecting to ACINQ node directly. When using Blockstream node or Federal Reserve - mostly failures. Maybe they run some older software .... ?

**Comment by sstone** [comment]
@charltonh FWIW I have tried the same setup (one channel to bitrefill) and can pay yalls without problems. How many channels do you see in the network view (click on the menu button in the top right corner and select `Network Overview` and check the `Known channels` field) ?

**Comment by sstone** [comment]
@irekzielinski not sure about Federal Reserve but Blockstream's node should be up to date

**Comment by sstone** [comment]
@charltonh I forgot to mention that #recksplorer will show you channel capacities but not how it is split between funder/fundee so if a lot a payments went through, all in the same direction, then the max amount you can pay in that direction becomes limited even if the channel's capacity is fairly high (I don't think it's your pb though)

**Comment by charltonh** [comment]
Just tried making a payment again to yalls at 039cc950286a8fa99218283d1adc2456e0d5e81be558da77dd6e85ba9a1fff5ad3@34.200.252.146 with another failure (same message).  The number of known channels I have right now is 5456.

**Comment by charltonh** [comment]
I opened a channel to an ACINQ node and am still having the same problem.  I now have 3 lightning channels open, but it doesn't even seem to be trying to find a route.  It instantly comes back with payment failed:
#1 of 1: LocalFailure
Cause: The wallet could not find a path to the payee
Origin:  Your node

I also tried uncapping the 3% fee option.  I have been able to pay other things before with this wallet and installation.  But most of my payments fail, especially to yalls (it worked once though).
I have to wonder where it's getting its routing algorithm/information.

**Comment by irekzielinski** [comment]
Yalls does not work me anymore as well. Maybe it's due to them moving the node:
https://mainnet.yalls.org/articles/97d67df1-d721-417d-a6c0-11d793739be9:0965AC5E-56CD-4870-9041-E69616660E6F/3120cef6-ff89-48d7-9845-535b513a5a3c

What never worked for me is sending tips to: http://reckless.lnroute.com/
I have a node with ACINQ and Blockstream.

**Comment by pm47** [comment]
@charltonh are you sure you were using the mainnet version of yalls? Url is https://mainnet.yalls.org

@irekzielinski same here, I think they may be experiencing issues. I just created a channel ACINQ --- lnroute, was probably a liquidity issue

**Comment by irekzielinski** [comment]
@pm47 - I reached owner of lnroute on twitter and he claims that channel is well funded (and has multiple paths): https://twitter.com/benvh/status/987303846170058752

mainnet yalls also fails - looks like some other issue in play here, possibly not the liquidity.

**Comment by pm47** [comment]
@irekzielinski  I'm able to tip him from eclair wallet through ACINQ node

regarding yalls, indeed it is not related to liquidity, see: https://github.com/lightningnetwork/lnd/issues/1082#issuecomment-383154618

**Comment by charltonh** [comment]
@pm47 I'm embarrassed to say that immediate failures with "The wallet could not find a path to the payee" was indeed to yalls.org articles and not mainnet.  I'm still unable to pay mainnet articles but the result is different (forever in 'PENDING' state, even though I have three prominent channels open).  As I mentioned, I was able to pay yalls before on mainnet but it was under a different section of the website.

I wonder if there's a way to direct which open channel the payment is going to go through?

**Comment by charltonh** [comment]
Just checked again and these txns are still in 'PENDING' state.  There should be the ability to cancel or fail after XX number of seconds, because at the POS by this time the client would have already used another form of payment.

**Comment by irekzielinski** [comment]
@charltonh the same: for some old payments to yalls those are in PENDING state.
Tried today:
- yalls mainet : SUCCESS
- coinpanic comunity jar: SUCCESS
- donate to lnroute.com: SUCCESS
- donate to rompert.com/recksplorer : SUCCESS

Few minutes later tried to do another coinpanic donation and this failed.
Not sure what changed - but looks better!

**Comment by pm47** [comment]
> There should be the ability to cancel or fail after XX number of seconds

@charltonh @irekzielinski unfortunately that's not something that can simply be "fixed" in eclair-wallet because of the way lightning works: only the last peer in the route (not necessarily the destination, but one that hasn't yet forwarded the payment to another peer) can fail-fast an htlc. Otherwise we have to wait for a timeout, and there is not much else to do.

Keep in mind that when using eclair-wallet, you are not only testing the app but the whole network, which is still very new and unreliable, and will only improve from now

I'm closing this ticket, as the main issue has been resolved and I'd rather not mix issues. Thanks!

**Comment by charltonh** [comment]
Tried it today and it WORKS!!

**Comment by Giosystem** [comment]
Yeah same issue I cannot send any payment to every channel I have tried. Keeps saying payment failed -(Local) path not found. Anyone able to help me here. I even have two lightning nodes set up at home.One in my garage, and one in my office they both have channels opened up to each other from both sides. I can’t send a payment to either of them from both sides as well. Same error eclair payment failed -(Local) path not found..... other. Help! Please Help!!
