### ISSUE TITLE
payment expiry is too close to the current blockheight

### ISSUE THREAD

**Issue by Alex-CodeLab** [ACINQ/eclair-mobile#57]
I'm getting this error when making a payment  (to a CL node) : 
       "payment expiry is too close to the current blockheight for safe handling by the relaying node." 

What does it mean and what can be done about it?

**Comment by sstone** [comment]
It means that the node that created the payment request set an expiry (in blocks) that is too close to the current block height. Processing it may result in an error that would cause the channel to close. There is not much you can do unless you control the receiving node,

**Comment by Alex-CodeLab** [comment]
I do control the receiving node, and I've set the expiry date (in seconds) far in the future. But it still fails.
I removed/closed  my channels to that node and made new channels. issue seems to be gone now. 
Could a node on the route cause this?

**Comment by sstone** [comment]
There are 2 expiries in a [BOLT11](https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md) payment request:

- the request expiry, which is basically is a warning that says "you have X minutes to send your payment" and is mostly a UX field. This is what you can set from the command-line when you create a request
- the actual HTLC time-out, which is  a low-level LN parameter that specifies when a node will be able to get their funds back when they send an HTLC and the other node does not send the payment preimage back

In your case it's the HTLC expiry that is too low. With lightning-c, you can configure it with the `--cltv-final` option, I suggest using 9 (their default is 6 which really is too low, see https://github.com/ACINQ/eclair/issues/526)

**Comment by Alex-CodeLab** [comment]
thanks!
I had to set `--cltv-delta` to 10 make it work

**Comment by parmax** [comment]
I nad to set --cltv-delta 10 --cltv-final 10 make it work
