### ISSUE TITLE
Tried to pay: https://ludvigart.com/product/test/

### ISSUE THREAD

**Issue by bitcoinuser** [ACINQ/eclair-mobile#59]
Tried to pay: https://ludvigart.com/product/test/

![photo5098451524580911183](https://user-images.githubusercontent.com/1178856/38964561-c44ff58a-434d-11e8-80f4-4c8456e41048.jpg)

**Comment by sstone** [comment]
See our [FAQ](https://github.com/ACINQ/eclair-wallet/wiki/FAQ#why-do-some-of-my-payments-fail-with-an-expiry-too-big-error-). node 033ce... is asking for a huge 1000 blocks cltv delay which makes it really hard to route through it. In the short term there is not much you can do now except open a direct channel to the node that you want to pay.

**Comment by bitcoinuser** [comment]
Ok.
