### ISSUE TITLE
This is not a valid node URI

### ISSUE THREAD

**Issue by benma** [ACINQ/eclair-mobile#64]
Hi

I can't scan/paste any node URI to open a payment channel, so the only channel I could open was to ACINQ.

The error I get everytime is: `This is not a valid node URI. Expected format is nodeId@host:port`.

Trying to scan URIs like `03aa6a60bc8570d057de350cd10dc9d988f14321dd3a225e81d9ca01b51674aae7@176.9.28.202:9735`.

Do you know what could be wrong?

Please let me know what info I need to provide (I am not experienced with Android app development). I did study the relevant code parts and unit tests, it looks like it should work.

Once I got the channel to ACINQ, I also had a similar issue with paying an invoice: it couldn't be parsed. It was a normal invoice, like `lnbc2340n1pdwp9k6pp5vachenfm4xah6fj077ayaemc50gjdryc385pnuht7htpdg309tssdq6f38zq3tcwpkx7un9wgs9g6tswvcqzysuylny39n0mx73t03jj8jaw9erxgppsg0a38ee58w62p4mzzcdrxzmn3ypzu54y6apnjum8j29j2lrdj4lfqqw47ec72espcph4elwlqqtxpcdk`.

**Comment by sstone** [comment]
How to you create the QR code for your URI ? I went to https://www.qr-code-generator.com, pasted 03aa6a60bc8570d057de350cd10dc9d988f14321dd3a225e81d9ca01b51674aae7@176.9.28.202:9735, chose `Text`, generated a QR code which I could scan from my phone with eclair. I did the same with your payment request and it worked too.
Can you try this ?

**Comment by benma** [comment]
Well, I'll be damned. Using the qr code generator you linked works perfectly! I was using `qtqr` before (also text mode), and both the eclair app to scan it as well as using another Android qr code scanner so I can copy and then paste it into eclair resulted in the same error. I saw no difference or encoding/decoding error in a visual inspection...

Anyway, thanks!
