### ISSUE TITLE
Some funds not available

### ISSUE THREAD

**Issue by feriancek** [ACINQ/eclair-mobile#68]
Funded wallet with 2 transactions of the same value confirmed in 2 different blocks, when the wallet opens It displays the true balance for a brief moment, before changing to display the following ignoring one of the two transactions:

![image](https://user-images.githubusercontent.com/5081442/39409051-751c7b98-4bb6-11e8-8930-041823eea83f.png)

Attempting to fund a channel returned not enough funds. So I went to bed, assuming more confirmations would help. Today I was able to fund a channel for 100k sat, at which point the total wallet value updated correctly: 
![image](https://user-images.githubusercontent.com/5081442/39409074-f347e714-4bb6-11e8-8290-2dc127e04b6c.png)

I'd say this is an issue with how the ui treats unconfirmed/low confirmation transactions, maybe a hold-over from testnet? I imagine the code saw the first as confirmed and available with the second still pending 6+ confirmations, but this was far from clear as both transactions have a green highlight for # of confirms.

**Comment by pm47** [comment]
Were two incoming txs sent to the same address? Can you paste the full txids here?

**Comment by feriancek** [comment]
Unique receiving addresses, separate blocks.
`639a347a4a7d68c0ba3dcc618ef2redacted`
`1d7e85757d8a517d243f547ab531redacted`

**Comment by feriancek** [comment]
Issue seems related to #22

**Comment by pm47** [comment]
Can I ask what wallet you used to send those txes?

**Comment by feriancek** [comment]
[Samourai](https://github.com/Samourai-Wallet/samourai-wallet-android)

Spent using [Bip126](https://github.com/bitcoin/bips/blob/master/bip-0126.mediawiki) enabled

**Comment by sjohnsson** [comment]
![screenshot_20180504-233011](https://user-images.githubusercontent.com/38996935/39659317-bda47802-4ff3-11e8-831b-aa9d31ad4359.png)

Same issue. Funds sent from ledger wallet.

**Comment by sstone** [comment]
We have identified and fixed this issue, the fix will be included in the upcoming release. Funds are not lost, it is a problem with how we compute your balance.

**Comment by feriancek** [comment]
Commit #?

**Comment by sstone** [comment]
@feriancek commit was https://github.com/ACINQ/eclair/commit/75437cbe811a95a6cd1ca6be7ec99d087e4edb47 which has not been merged in our android branch yet, but will be very soon
