### ISSUE TITLE
BIP39 vs BIP49

### ISSUE THREAD

**Issue by DanielWeigl** [ACINQ/eclair-mobile#7]
I guess you mean BIP39 here:

https://github.com/ACINQ/eclair-wallet/blob/a0a2758d7b0fedb1099b903f8ea129e1b6dbf774/app/src/main/res/values/strings.xml#L77

BIP49 is also somewhat correct in this context, but i guess the intended meaning was BIP39, or?

**Comment by sstone** [comment]
Yes, "a BIP39 seed with a BIP49 derivation path" is probably more correct here

**Comment by prusnak** [comment]
I confirm that "a BIP39 seed with a BIP49 derivation path" is probably the best formulation.
