### ISSUE TITLE
Support for global FIAT currencies

### ISSUE THREAD

**Issue by ghost** [ACINQ/eclair-mobile#71]
The wallet features EUR and USD, but it should support all global fiat currencies 🌎 

Some providers:
* Bitpay
https://bitpay.com/rates
* Coindesk
https://api.coindesk.com/v1/bpi/currentprice/JPY, https://api.coindesk.com/v1/bpi/currentprice/BRL

**Comment by ghost** [comment]
Cool, the wallet has now 22 currencies! It certainly covers the most important ones, and it covers all my uses, but I'm wondering why you didn't pick https://bitpay.com/rates since it gives more than 100 currencies in a single call. Licensing issues I guess?

**Comment by dpad85** [comment]
That's for technical reasons. Bitpay API returns an array which you have to parse. I prefer using the blockchain.info API where each currency is an object that you can retrieve with its code. It makes for a cleaner code.
