### ISSUE TITLE
Issue with cracked screen stopping from putting in the pin

### ISSUE THREAD

**Issue by CaveRock** [ACINQ/eclair-mobile#75]
Wallet is fine and functional, however after dropping my phone, a section of the screen no longer recognises any touches, unfortunately the section happens to cover one of the numbers i need to enter my pin, the number 8.

I know this is an edge case, and the funds I have in the wallet are small enough that I am not concerned with losing them, but it shows up a scenario where the app state is fine, but the users phone is causing issues getting access. Is there a way for me to copy raw files/local db to get the channel ids and latest states off the broken phone and onto a new one?

I know in my case just allowing the use of the keyboard with a text box to enter the pin would allow me to get access, but the greater question I guess is about backups of the wallet to mitigate this issue going forward.

Before the screen crack the app was working great! Picked up some stickers with it.
Thanks for the hard work.

**Comment by molxyz** [comment]
@CaveRock  Do you have the word seed?  Install the app on another phone, put in your seed and it will restore the wallet with the onchain fund.  Currently it can't restore your channels but can restore the wallet.

**Comment by CaveRock** [comment]
@molxyz yup, I've got the seed but most of the funds are in the channel. Thought it might be the case at this stage that the channel funds might be lost, it's a small amount so no worries on that front.

**Comment by masrlinu** [comment]
In android you can split the screen, so on top you have the eclair app and on the bottom you have another app. Like this the number 8 is on another position on your device. You can even move the eclair app more to the top and make it smaller, if you still cannot press the number.

**Comment by CaveRock** [comment]
@masrlinu great suggestion! I wasn't able to do exactly as you suggest as the phone is an older xiomi and their additions to the OS seem to have hidden any options for split screen, however I was able to use One Handed mode in combo with full screen (one handed mode obscured a different key I needed in the pin) and was able to get the pin submitted.

Thanks for the out the box thinking!
