### ISSUE TITLE
leaking private channel info

### ISSUE THREAD

**Issue by robtex** [ACINQ/eclair-mobile#76]
i strongly suspect eclair is sending channel updates for private channels.
not the announcements, only updates.
that might be a minor privacy issue. please have a look.
too lazy to dig up evidence before you have a quick look first 
cheers!

**Comment by pm47** [comment]
Yes eclair does send `channel_update`s for private channels, but only to the node it has open the private channel with. This is the correct behavior, see BOLT 7:
> [A node] SHOULD accept channel_updates for its own channels (even if non-public), in order to learn the associated origin nodes' forwarding parameters.

Those `channel_update`s can't be publicly broadcast, because, as you noticed, they are not backed by a `channel_announcement`:
> [A node,] if the short_channel_id does NOT match a previous channel_announcement [...] MUST ignore channel_updates that do NOT correspond to one of its own channels

**Comment by robtex** [comment]
ok. i'm seeing this from a node that doesn't have any channels, private or otherwise, so some implementation is relaying the channel_updates anyhows. 
here are a few channels i believe should be private and not gossiped, hope someone reading this recognizes them. otherwise i'll go hunting down exactly which nodes send them
573399711980126208/521504:739:0
573393115016200192/521498:2354:0
573393115016134656/521498:2353:0

**Comment by pm47** [comment]
Just to be clear: you have a node A that doesn't have any channels, connected to an eclair node B, and A receives these `channel_update`s from B?

**Comment by robtex** [comment]
hi. i tracked it down to c-lightning
eclair wallet is connected to node A via private channel
node A gossips message 258 (both flags) about the channel to peer B (that doesn't have any channels at all)
node A is a c-lightning
added an issue on clightning https://github.com/ElementsProject/lightning/issues/1485
think you can close this here. i'll keep an eye on it globally

**Comment by pm47** [comment]
Ok closing this, thanks!
