### ISSUE TITLE
Not Enough Balance to Send Bitcoin Mainnet Lightning Payment . . . But There Is

### ISSUE THREAD

**Issue by KibbledJiveElkZoo** [ACINQ/eclair-mobile#8]
I have a problem with the program saying there are not enough funds while there appear to be enough funds, too.

I get the message: "None of your Lightning channels has enough balance to send this payment.", when trying to pay a 1,090 microbitcoins (1.09 millibitcoins) BitRefill.com order. I have a channel with BitRefill's node that has 1,122 microbitcoins (1.122 millibitcoins) in "NORMAL" status. #confused

**Comment by sstone** [comment]
Yes, you cannot send all (or almost all) of your balance, you have to keep some of it:
- you need to maintain a reserve (which you can see in the "Channel Details" view when you select a channel)
- and you must also keep enough funds to pay for the on-chain bitcoin fees (the state of your channel has to be publishable, this is what enables you to close your channels whenever you want even if the peer you are connected to is gone).

**Comment by KibbledJiveElkZoo** [comment]
Thank you for the insight.  That helped me understand better.

**Comment by mautematico** [comment]
I am facing that same issue.

It is really annoying that there is no clear info about how much you must keep. I have 131k satoshis and are unable to open a channel with 100k capacity.

**Comment by mautematico** [comment]
I put a few extra satoshis and now I understand it:
Eclair forces you to keep at least 100ks available onchain  to open a  channel, like this:

![imagen](https://user-images.githubusercontent.com/1238928/38448279-cf725266-39c8-11e8-9fe8-04f6009c4173.png)

**Comment by mautematico** [comment]
And... they are fixing it.

https://github.com/ACINQ/eclair-wallet/commit/35ee943c7b21ce214d9852d35f3e9cab4161ae13#diff-e5c0452da704b2a3f36bb8616334352bL26

**Comment by dpad85** [comment]
Fixed by https://github.com/ACINQ/eclair-wallet/pull/11.

Closing this, thanks!
