### ISSUE TITLE
Bitcoins lost in the channel 

### ISSUE THREAD

**Issue by novomirskiy85** [ACINQ/eclair-mobile#81]
Hello, this is a problem...

I put on my ACINQ btc-address 0.05 btc(16 of April), opened LIGHTNING channel with 0.049 btc, used it with pleasure until  27 of May becose have 2 or more failed lightning-payment via BITREFILL service after that lightning channel closed automatical and non-spent bitcoins returned back to my blockchain address 0.03233(247 USD). i opened the new lightning channel with 0.03 btc(226 USD) and Try to make 2 lightn-payment but it was fail(bitrefill.com).. 1 of June i closed the last channel by my hand, but bitcoins gone! i expected that if you close the channel manualy non-spend bitcoins come back to main wallet(btc address), but i got 0.001656 btc ($12.51) refund! Is that right and where was I  wrong?

sorry for english and noobing =/

![d1uclqnlqfk](https://user-images.githubusercontent.com/39875745/40885367-93154cb4-672d-11e8-8a39-181d22aca27f.jpg)
![cbbfiyqufk4](https://user-images.githubusercontent.com/39875745/40885369-997d8d46-672d-11e8-8906-c2ddd4298479.jpg)
![v9bdmlinjyq](https://user-images.githubusercontent.com/39875745/40885370-9e74335e-672d-11e8-9578-644873537bdb.jpg)
![wtajf4h8inm](https://user-images.githubusercontent.com/39875745/40885371-a0d18ea8-672d-11e8-9dd5-8015f0c215d3.jpg)

**Comment by dpad85** [comment]
Hi, what version of the wallet are you using? You can see that in the Menu > About page

**Comment by novomirskiy85** [comment]
0.3.0 version

**Comment by dpad85** [comment]
The 0.3.0 version has a bug with uncooperative closing where funds are not recovered (this is your situation). This was reported in https://github.com/ACINQ/eclair-wallet/issues/17, so I'll close this issue as a duplicate.

There is a step-by-step tutorial that will allow you to recover funds that are stuck: https://github.com/ACINQ/eclair-wallet/wiki/Recover-funds-stuck-in-CLOSING-state-from-Eclair-Wallet-0.3.0

Please report back here to tell me how it went, thanks!

**Comment by novomirskiy85** [comment]
done it! thank you very much ;))
