### ISSUE TITLE
[Feature] Unlock via Fingerprint reader

### ISSUE THREAD

**Issue by prusnak** [ACINQ/eclair-mobile#9]
Allow unlocking the wallet via fingerprint reader instead of PIN entry.

**Comment by prusnak** [comment]
Relevant documentation:
* https://developer.android.com/about/versions/marshmallow/android-6.0#fingerprint-authentication
* https://developer.android.com/reference/android/hardware/fingerprint/package-summary
* https://proandroiddev.com/5-steps-to-implement-biometric-authentication-in-android-dbeb825aeee8
* https://willowtreeapps.com/ideas/android-fingerprint-apis-an-overview-for-android-app-developers

**Comment by dpad85** [comment]
Thanks for the documentation! This is indeed a needed feature, entering the pin every time is growing tedious. If all goes well this is one of the next addition to the wallet 😄
