### ISSUE TITLE
Feature request: Allow setting the Electrum node address

### ISSUE THREAD

**Issue by whizz** [ACINQ/eclair-mobile#91]
As a user, I'd like to be able to use my own Electrum server for better privacy. The settings should allow me to specify custom Electrum address and port.

Thanks for considering adding this option.

**Comment by Kixunil** [comment]
I'm interested in this feature as well, especially because I already have an Electrum server.

**Comment by pm47** [comment]
+1, this is something that we have meaning to add for quite some time

**Comment by dpad85** [comment]
This feature will be available in the next release. Please note that the electrum server you connect to will need a valid certificate.
