### ISSUE TITLE
Logo Proposal: Eclair-wallet

### ISSUE THREAD

**Issue by baranpirincal** [ACINQ/eclair-mobile#93]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by dpad85** [comment]
Hi Baran, thanks for the offer!

I'm fine with the logo of the project right now ([it's the wireframed version of the eclair logo](https://raw.githubusercontent.com/ACINQ/eclair-wallet/testnet/app/src/main/res/drawable/splash_image.png)), but it can certainly be improved.

There are also several icons in the project that need an update. [The current version of the send payment icon](https://raw.githubusercontent.com/ACINQ/eclair-wallet/testnet/app/src/main/res/mipmap-xxxhdpi/ic_send.png) is very generic and does not convey the actual meaning of the button. If that's something you're interested in, that would be great!
